### ISSUE TITLE
Inbuilt panel launcher applet: ended up with a duplicate when I should not have

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/cinnamon-spices-applets#1085]
Mint 18.2
Cinnamon 3.4.4
Version of applet: it's 'about' button doesn't report it, but I think it's the most current version.

I was editing the applet's configuration, through its GUI. Whilst doing that, in another window, I moved the file the applet runs. That seemed to make the applet config window, and the applet itself on the panel, disappear. I recreated the applet. At that point, two versions of the applet appeared on the panel - duplicates of each other.

I don't have a glass.log file.

.xsession-errors seems to contain nothing relevant, but it is hard to tell, because something else seems to be filling that log (I can't tell what the something else is, but I know those error messages pre-existed the problem I have just had) and the log seems to contain no timestamps.

**Comment by jaszhix** [comment]
> I moved the file the applet runs.

Why? You're not supposed to do that. If you move it to where Spices applets are located, it will override the other applet in /usr/share/cinnamon, unless you change its uuid. In any case, I don't think what you're doing is a normal use case, or should be considered a bug because it takes a lot more man hours to workaround that in code, when you can simply not move system files around.

> hard to tell, because something else seems to be filling that log

You should paste the log, we're not mind readers.

Stock applets shipped with Cinnamon need to have their issues opened in the [correct place](https://github.com/linuxmint/Cinnamon/issues?utf8=%E2%9C%93&q=is%3Aissue%20launcher).

**Comment by CottonEaster** [comment]
I seem to have been unclear. The file that I was moving was _not_ a system file. Rather, it was the file that is run by the launcher in question.

I will post a clearer version of this bug report, with a log, in the correct place.
