### ISSUE TITLE
redshift@marvel4u: Icon does not scale with panel size

### ISSUE THREAD

**Issue by sphh** [linuxmint/cinnamon-spices-applets#1128]
Have you read the guidelines for contributing?

Before opening an issue, please read the guidelines for contributing linked above. Issues with invalid formats, or issues not mentioning the maintainer of the applet, may not get a response, and eventually will be closed. You can find the author by visiting the applet's page on the Spices website (https://cinnamon-spices.linuxmint.com/), or going to the applet's directory on this repository, and checking the the author field in info.json. If it is set to none in info.json, or there is no author listed on the site, then this step is not necessary.

[Notify author of applet]: @Marvel4U 

 - Distribution: Linux Mint 18.2 Sonya
 - Cinnamon version: Cinnamon 3.4.4
 - Applet version: 2.0.0

[Issue]: <> (Describe your issue below.)
As the subject already say: The applet's icon does not scale if I increase the size of the panel.

**Comment by NikoKrause** [comment]
issues not mentioning the maintainer of the applet, may not get a response

**Comment by sphh** [comment]
Thanks @NikoKrause for pointing this out.

I simply filled in the template when opening a new issue. This has the line

``[Notify author of applet]: <GithubAuthor>``

where I replaced the ``<GithubAuthor>`` with @Marvel4U but this line does not show up in the final message …

@Marvel4U could you please look into this bug report.

@NikoKrause could you please look into the template.

Thanks to both of you!

**Comment by Martin1887** [comment]
This is weird, since icons are svg. I have modified my panel height in a exagerated way to check the issue and I think that the icons scale fine (red sunset):

![imagen](https://user-images.githubusercontent.com/4211771/29134122-fd4a8a6e-7d35-11e7-852c-ec3f8a4ed671.png)


Could you please provide a screenshot?

Thanks and regards.

**Comment by sphh** [comment]
I set the slider for the panel height in the panel settings as far to the right ("larger") as possible. Please also note that it's a top panel and it's set to transparent with shadow in the "Transparent panels" extension. "Allow Cinnamon to scale panel text and icons according to the panel height" is "on".

![screenshot from 2017-08-09 23-13-07](https://user-images.githubusercontent.com/4856462/29146631-1c35e2e2-7d5a-11e7-8e0a-b70cbf3d5d79.png)

All but three applets scale to this height. I admit, it's hard to see the bottom, but the "line" in the CPU field shows the bottom line.

These three applets are the "Multi-core System Monitor" multicore-sys-monitor@ccadaptic23 (you can set its height in its configuration), the "Countdown timer with notification" axos88@countdown-timer (that tiny alarm clock) and Redshift. Maybe the problem is the "Drawer (show/hide applets)" show-hide-applets@mohammad-sn?

**Comment by Martin1887** [comment]
Hello @sphh.

This seems a Cinnamon bug, since I also set panel height to the maximum and my applet was enlarged as you can see in my screenshot. Without reproducing the problem it is really difficult solve it, and it also seems that applet code and assets has nothing to do to solve the issue, since the icons are SVG.

Have you tried to move the Redshift applet to another position inside the panel and check if its size is changed? 

Have you tried to remove the applet and to add it again?

Which Cinnamon version do you have?


Thanks and regards.

**Comment by NikoKrause** [comment]
Also can.you try it without the show/hide applet and on another panel?

**Comment by Marvel4U** [comment]
Hello,
I encounter this issue every time when I add the applet but it's appropriately resized when changing anything on the panel (like activating the panel editing mode).
I played around with this issue and it seems that the redshift applet inherited it from the simple brightness applet. I suspect it can be fixed by loading the icon in a different way. (For example the brightness-and-gamma applet doesn't have it.)
I'll report back when this idea works out.

**Comment by sphh** [comment]
Hi @Marvel4U 

I just wanted to write up my experience after playing with it a bit this morning:
* If I add the applet to a normally sized panel and change the panel size afterwards, the icon is sized accordingly.
* If I add the applet to a larger panel (have not tried it with a smaller panel), the icon is too small. Activating the panel edit mode changes the icon to the correct size.

This is actually exactly what you observed!

Thank you for taking my report seriously.

Would it help to file a bug against the other applets? All of them seem to suffer the same problem and maybe some of the other developers have already figured out how to handle this?

**Comment by Martin1887** [comment]
Maybe pull request #1170 fixes this issue. @sphh, could you please try it?


Thanks and regards.

**Comment by sphh** [comment]
Today I updated the applet and the icon scaled appropriately. I also restarted Cinnamon, dis- and subsequently enabled the applet and the icon scaled all the time. It looks like you squashed that bug!

Thanks.
