### ISSUE TITLE
bumblebee@pdcurtis: bumblebeed executable wrong location

### ISSUE THREAD

**Issue by KickerTom** [linuxmint/cinnamon-spices-applets#1136]
@pdcurtis:
First, thanks a lot for the great applet. It really helps me to keep track of battery consumption, i.e. make sure the nvidia graphics runs only when using external display.
However, after updating from some ancient version to the latest one, I started getting errors about missing bumblebeed binary. At least on my LMDE, bumblebeed is installed to /usr/sbin, but the applet is using path of the logged in user when searching for it (which does not contain /sbin or /usr/sbin).

I have added a small hack to the applet which seems to resolve the issue for me (which may not be the best solution, but it should illustrate the problem quite well):

```
--- applet.js   2017-08-11 08:54:05.466916178 +0200
+++ applet-orig.js      2017-08-11 08:55:21.567364789 +0200
@@ -145,8 +145,6 @@
             }
 
             // Check that Bumblebee Daemen is installed 
-            let path = GLib.getenv("PATH") + ":/sbin:/usr/sbin";
-            GLib.setenv("PATH", path, true);
             if (!GLib.find_program_in_path("bumblebeed")) {
                  let icon = new St.Icon({ icon_name: 'error',
                  icon_type: St.IconType.FULLCOLOR,

```

**Comment by pdcurtis** [comment]
@KickerTom @jaszhix I will have a look at this. 

On my machine bumblebeed is in /usr/sbin which is where I would expect and PATH includes /usr/sbin and /sbin and this was checked on Mint 18 and 18.1, 18.1 and 18.2. Is this a feature of LMDE ?
If necessary I will remove the check altogether as there is already a check of the contents of /proc/acpi/bbswitch which catches the error of bbswitch not running and hence bumblebee not being installed.

@jaszhix @NikoKrause  @Odyseus Does anyone know better and more foolproof and elegant checks for installed programs and/or file presence which are checked to work on LMDE and Mint?

**Comment by jaszhix** [comment]
Take a look at menu applets. Specifically, the code handling building the categories also can handle fetching the desktop apps by iterating ```app_system.get_tree()```.

**Comment by KickerTom** [comment]
> On my machine bumblebeed is in /usr/sbin which is where I would expect and PATH includes /usr/sbin and /sbin and this was checked on Mint 18 and 18.1, 18.1 and 18.2. Is this a feature of LMDE ?

Looks like this really is a difference between Ubuntu and Debian (thus also between Mint and LMDE). Debian just does not add /sbin and /usr/sbin to the path of any other user than root. E.g. here is a related comment:
https://unix.stackexchange.com/questions/232782/is-there-a-reason-i-would-not-add-usr-local-sbin-usr-sbin-sbin-to-my-path-o

> Take a look at menu applets. Specifically, the code handling building the categories also can handle fetching the desktop apps by iterating app_system.get_tree().

Isn't get_tree() being obsoleted in recent gtk? But mainly, will this return also programs which have binaries not in path, and not in the menu system? Bumblebeed is not an desktop app...

Personally, I do not see much reason to check for bumblebeed binary at all, it is not being executed by the applet. It's the /proc/acpi/bbswitch which is used, and which should be (and already is, as you stated) checked for existence, correct? So maybe doing explicit check for the bbswitch file in place of the binary check and displaying the error if not found would make more sense.

Anyway, thanks for your fast response and your time you spend on this.

**Comment by pdcurtis** [comment]
@KickerTom I had already started to remove the check as a short term fix. The logic in the extra check was to give a warning which included an indication of what to do before the applet loop started to run. I can do the same with a check of the presence of /proc/acpi/bbswitch at the start but my current code lacks elegance at present. 

The check for a daemon/program by GLib.find_program_in_path("program") is also used in other applets (including another of mine and 7 others) as a check for dependencies and in fact I was advised to use it to ensure dependencies were met in applets. Your input is valuable as I had no idea that Debian and Ubuntu differed in this important aspect.
 
@mtwebster You may be interested or even wish to take part in this conversation!

**Comment by mtwebster** [comment]
Huh I didn't know that about LMDE.  

This is sort of an ugly area - I hate snooping around files from an applet, but it's unavoidable.

Definitely for executables, g_find_program_in_path is best - as mentioned the app sys works from our menu tree, which is populated solely via desktop files.

For normal files, I'd use g_file_test - *don't* use g_file_query_exists (it blocks).  Using g_file_query_info, you can construct an asynchronous version of checking whether a file exists, but I'm not sure it's worth it here, g_file_test should do the trick.   It does make me wonder if we would benefit from a nice rolled-up function that any applet could use - an  asynchronous file existence check.

**Comment by pdcurtis** [comment]
@mtwebster I had found GLib.file_test and was looking at something like   
`this._isFileInstalled = GLib.file_test('file', GLib.FileTest.EXISTS);`
but had not though about the issue of synchronous and asynchronous but I have got as far as finding it is used in quite a number of applets so it looked a good bet.

How does one know if functions are asynchronous?

Your idea of a nice rolled-up function that any applet could use - an asynchronous file existence check seems sensible or a well tested example for people to follow when checking for 'dependencies' being met for an applet.

Is there actually anything against using try and catch with a file read as an alternative if one has to eventually read a file's contents as I do in my bumblebee applet?

One of the major problems I find with use of the synchronous functions is that it trips the dangerous flag and associated warnings which puts people off using applets regardless of whether it is a real problem or not - do we need a mechanism for reviewing applets so that the warnings can be removed or at least tone down if problems are unlikely?

**Comment by pdcurtis** [comment]
@KickerTom I think I have found a very simple fix for the applet which is to check for the presence of optirun instead of bumblebeed as optirun is in /usr/bin and should be just as good a check that bumblebee is installed.

Can you confirm that solves the problem under LMDE and I will generate the Pull Request.

**Comment by KickerTom** [comment]
I am sorry for late reaction. Tested it now (update from oficial repo, now you merged it) and it works perfectly. Thanks a lot for such a fast fix.
