### ISSUE TITLE
Window List With App Grouping and Linut Mint 18.1

### ISSUE THREAD

**Issue by magellan-13016** [linuxmint/cinnamon-spices-applets#114]
Hi !

First of all many thanks for the amazing job making cinnamon panel more user friendly for people coming from Windows OS.

Since last Mint update, there is no way to display the thumbs over the icon. So please update the applet for the last Cinnamon included in Linux Mint 18.1

Thanks for advance. 

David.

**Comment by NikoKrause** [comment]
Yeah It's abandoned. Meanwhile you can try the fork Icing Task Manager.

**Comment by magellan-13016** [comment]
Yes ! Ok for the fork ! I've tried it and it's more powerful. Many thanks for the information.

**Comment by jake1164** [comment]
@NikoKrause Is there a way to tag apps that are abandoned and / or not working?  Maybe something as lot tech as a list somewhere?  Perhaps an "abandoned" as the user in the .json file?

**Comment by collinss** [comment]
@jake1164 We actually have a google spreadsheet that we use to track them internally. It's not a complete list yet of course, because it takes time to go through that many, but also because we don't always know it's abandoned until the author fails to show up. With some of them it's pretty obvious though (comments going back 3 years saying "doesn't work" is a pretty good clue ;) ).
