### ISSUE TITLE
SpicesGeneral - Security Enhancement - Run applets from signed tar file

### ISSUE THREAD

**Issue by jake1164** [linuxmint/cinnamon-spices-applets#118]
The strides in the spice quality / development in last release has been huge.. But IMO it still is lacking from a users security perspective.  My suggestion as a starting point is to do the following:

Change the spices to all run from a tar file (or maybe a tar file or directory).  When cinnamon loads the applets it would check the tar file and if it is signed and valid signature then go ahead and display it (it knows at this point it matches what was installed and not been tampered with). Any other applets are either shown with a warning, or maybe a prompt to warn to start.  

This would allow users to install their own, and developers to install their own, but an end user can install an applet, know its secure, and not worry about something being changed in the back end by other processes.

Once again I understand this is not totally an applet issue, but if you point me where to add it I can, but I think the applet developers feedback could be useful none the less.

**Comment by collinss** [comment]
It's all in the user's home folder, so couldn't some nefarious software simply change the signature as well?
The only way to make this work would be to require root access to install. But honestly, if something is able to change the files in your home folder, you have bigger issues. I don't see this as any better than the current situation, personally.

**Comment by jake1164** [comment]
Not if you used a Cryptographic Signature, ie RSA Public / Private keys. The repo would hold the private key and when the code is submitted and approved it would create the tar and sign the file.  The OS would hold a public key that would validate the signature on execution, or startup maybe.

You do have to have root to install applications so should applets be less secure?

**Comment by collinss** [comment]
Applets are not applications, they are more like firefox extensions, which also don't need root access to install.

Also, having the signature on the server means that the os would have to check the server whenever it checks the applets. For those who have consistent high-speed internet this is not a problem, but many do not.

Also, I feel that it would annoy many users for something that is almost a non-issue. I'm not a security expert but it seems to me the likelihood that someone would be able to utilize this to access someone's 
computer when other methods fail is negligible.

You'll have to check with @clefebvre since he's the one who will make that call, but I personally don't see the point.
