### ISSUE TITLE
UUID: multicore-sys-monitor@ccadeptic23 - adding disk health indicator

### ISSUE THREAD

**Issue by dhdurgee** [linuxmint/cinnamon-spices-applets#1443]
**Notify author of applet**
@

**Issue**

I am in the process of recovering from a hard drive failure.  It would have been great if had been an indicator of some sort in my cinnamon panel telling me how healthy my hard drive is.  I understand that such data is available from the drive via S.M.A.R.T, but from what I have seen you can drown in details there and it takes understanding of the data to determine the state of the drive.

I would like to see a simple colored dot in the disk display colored green if the drive has no problems at all, yellow if there are signs of problems developing and red if the data on the disk is in danger of loss.

Any variant on this would be acceptable and would have warned me to buy an new drive and clone the current one prior to failure.

I am unaware of any other applet with such a feature and yours appears to be a good fit, so please consider this added function.

Dave

**Comment by jaszhix** [comment]
This is out of scope for the applet, sorry. There are already excellent tools available for anticipating data loss from HDD failure with `smartmontools` and the GNOME disks app included in Mint/Ubuntu. I think monitoring hard drives is something everybody should be a little hands on with. I wouldn't trust my data to an applet, personally. If it should exist, it should be a new applet because this multicore-sys-monitor is already seeing the effects of feature creep.
