### ISSUE TITLE
tracker@glebihan: Install dependencies when adding the Tracker search applet?

### ISSUE THREAD

**Issue by orschiro** [linuxmint/cinnamon-spices-applets#1563]
Dear all, 

This is a fantastic applet!

But the installation is not very user friendly. 

1. I go to "Add applets to panel"
2. I search and find this applet
3. I install it and add it to my panel

At this stage, I am just getting an error that doesn't tell me the root of the problem which is that I don't have the dependencies installed (sudo apt install tracker-gui gir1.2-tracker-1.0).

This information is only shown on the website of the applet but requires me to find this website in the first place. 

Can't we install the required dependencies when the user is adding a new applet to the panel which requires those dependencies?

Thank you!

**Comment by NikoKrause** [comment]
There are a lot of applets in this repo. Which one are you talking about? Please add it in the issues title.

**Comment by orschiro** [comment]
@NikoKrause I am sorry! I meant the Tracker search applet. I updated the title.

**Comment by NikoKrause** [comment]
Ah yes. That's always an issue. The problem is, that Cinnamon (and therefore it's applets) is not Mint only. It's a desktop used by different operating systems Ubuntu/Fedora/Arch, etc, which use different packaging systems. So installing dependencies automatically is a little bit difficult.
Most applets handle it by poping up a notification, that a dependency is missing. This can be done for this applet as well.

**Comment by orschiro** [comment]
> Most applets handle it by poping up a notification, that a dependency is missing. This can be done for this applet as well.

This would be great, @NikoKrause! :-)

Great idea.

**Comment by icarter09** [comment]
@brownsr this ticket can be closed. Applet has been removed.
