### ISSUE TITLE
Disk IO stat is wrong if Network stat is ON: UUID:multicore-sys-monitor@ccadeptic23

### ISSUE THREAD

**Issue by KES777** [linuxmint/cinnamon-spices-applets#1601]
```
 * v1.8.1/2017-12-26 07:50
 * Cinnamon 3.6.7
 * Mint 18.3; Linux work 4.13.0-26-generic #29~16.04.2-Ubuntu SMP Tue Jan 9 22:00:44 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
 ```
**Issue**

![delete](https://user-images.githubusercontent.com/799021/34904293-c1201798-f84b-11e7-881d-1eb9d79b331a.jpg)

**Steps to reproduce**

Turn ON: network stat and disk io stat

**Expected behaviour**

If there is no Disk IO it should shows 0 Bytes/s

**Comment by KES777** [comment]
this always reproducible when "Preferences" window is opened.

![delete](https://user-images.githubusercontent.com/799021/34904389-8c508f6e-f84d-11e7-99f5-0e88436955e9.jpg)

This gap when the preferences window is opened and remains until we close the preferences

Here we close the preferences:
![delete](https://user-images.githubusercontent.com/799021/34904394-b1b52616-f84d-11e7-8b33-55c7fc0b8106.jpg)

**Comment by jaszhix** [comment]
All the stats will be incorrect while preferences are open because it has to check if the settings have changed on an interval and reset the measurement. It gets those speed numbers by comparing two different timestamps, but if the timestamps constantly reset it breaks. These timestamps reset after every settings change, which occurs constantly to check for settings changes while prefs are open. I don't intend to fix this anytime soon since it doesn't impact normal operation.
