### ISSUE TITLE
WindowListGroup@jake.phy@gmail.com

### ISSUE THREAD

**Issue by LEGOlord208** [linuxmint/cinnamon-spices-applets#169]
(This is by @clefebvre, I think. He is the one who pushed the initial commit at least)
Hello! I think this... uhh... is how I'm supposed to contact you...

Anways, I have a little Java program which puts itself in the task bar.
Normally this is fine (even though the Java taskbar implementation is kinda awful).
But with Window List Grouping, I get a Java icon, like this:
![image](https://cloud.githubusercontent.com/assets/12830969/23584920/e17ec526-016f-11e7-94ab-08da8775df86.png)

I don't know if this is something you can do anything about. But I would love to see a fix for it, if possible.

**Comment by jaszhix** [comment]
That applet's abandoned, you can see if my [fork](https://cinnamon-spices.linuxmint.com/applets/view/269) of it fixes the issue, but I'm guessing it won't because the icons only display correctly if they have a ```.desktop``` file association for them in one of the directories Cinnamon looks in, such as ```~/.local/share/applications```. I don't use Java apps, so not sure if there's anything different you should do.

**Comment by LEGOlord208** [comment]
Thank you... A lot! For everything!  
For the fork, for telling me it exists!

It's just perfect!
... well, it doesn't fix the issue,  
but I can just move the icon to another workspace.

It just makes me incredibly happy to see that this project isn't abandoned =)
