### ISSUE TITLE
IcingTaskManager@json Incorrect old style of window titles and minimized windows

### ISSUE THREAD

**Issue by Martin1887** [linuxmint/cinnamon-spices-applets#1853]
```
 * Version 6.3.5
 * Cinnamon 3.8.1
 * Fedora 28
 * NVIDIA RPMFusion driver
 ```
 @jaszhix

**Issue**
When applications are switched, the previous application title continues with the same colour.

In addition, there is not any manner of identifying minimized windows. For instance, in the Cinnamon stock applications list they are shown inside square brackets.

**Steps to reproduce**
1. Open two applications. Switch from the second to the first with `Alt+Tab` or clicking in the first.

2. Minimize an application.

**Expected behaviour**
1. The second application is not the current focused application, so its title is grayed.

2. The minimized application has another style that identifies its state.

**Comment by jaszhix** [comment]
ITM checks focused, running, and pinned app button states. Minimized apps are not tracked. I have already done a lot of tail chasing trying to get themes to play nice in an unsupported manner with expressing "running" app styling that the Cinnamon CSS doesn't currently support, and this is very likely a theme problem I can't do much about currently. Please see https://github.com/jaszhix/icingtaskmanager/issues/199 as an example of this.

Also, always check the ITM repo first because that's where I prefer to track issues for it. I will try to keep track of bug reports here, but its not likely to make it into my note tracker app that integrates with the repo. Can you please provide the settings JSON and ~/.xsession_errors log? ITM's repo issue template applies to ITM issues here too because the repo is mentioned in the readme as the preferred bug tracker.

**Comment by Martin1887** [comment]
Ok, I close this issue to work in jaszhix/icingtaskmanager#199.
