### ISSUE TITLE
windows-buttons-with-title-2@hanspre: Where did it go?

### ISSUE THREAD

**Issue by moretocome** [linuxmint/cinnamon-spices-applets#1877]
```
 * Applet version/Build date 2017-08-17
 * Cinnamon version 3.8.6
 * Distribution - Mint 19
 ```

**Notify author of applet**
@

Does anybody know what happened to the "Windows Buttons With Title 2" applet? After upgrading to LM 19 "Tara" Cinnamon, I can't find it anywhere anymore.

Or perhaps someone know of another way to move the windows controls to the panel as pictured with red lines in this top right section of my desktop:
![Desktop screen shot](https://i.imgur.com/lXZlofX.png)

Thanks in advance :)

**Comment by smurphos** [comment]
Looks like it was removed as an unmaintained and zero scored applet with this commit back in Sept 17 - https://github.com/linuxmint/cinnamon-spices-applets/commit/ab94732a8b979fcaed20eb5d6486d9ad16e229bd

If you download a zip of the repo immediately prior to that commit via https://github.com/linuxmint/cinnamon-spices-applets/tree/940615c0621ed152cd65d65edc6be97866e1acb2 you can extract the applet files and manually install them. Be aware that the applet may not work in Cinnamon 3.8

**Comment by moretocome** [comment]
Thanks for clearing that up @smurphos 

I have the most recent version backed up from my LM18.3 install. Unfortunately it dies not work in LM19 with cinnamon 3.8 like you say.

So now I am looking for an alternative approach. It seems such a waste of screen real estate to use so much space for so little information :)

**Comment by Odyseus** [comment]
Hello, everybody.

@moretocome: Here is a fixed version of the [window-buttons-with-title2@hanspr.zip](https://github.com/linuxmint/cinnamon-spices-applets/files/2162829/window-buttons-with-title2.hanspr.zip) applet that will work on Cinnamon 3.8.x. I did some basic testing and the main features seem to be working normally. :+1:

**Comment by moretocome** [comment]
@Odyseus You sir, have won the internet!! :1st_place_medal: 
![Window-buttons-with-title2@hanspr](https://i.imgur.com/If1KRzP.png)
Thanks a lot! If i can upvote or do anyhing else to appreciate your work, please let me know :)

**Comment by moretocome** [comment]
Well thanks none the less. And I agree. This functionality was actually what made me switch from Mate to Cinnamon a few years back. And I also think that "zero score applet" is a little misleading.

Because the [Cinnamon Maximus](https://cinnamon-spices.linuxmint.com/extensions/view/29) is quite popular with a score of 11 (2nd most popular extension).

There used to exist several other applet options for manipulating the windows in Cinnamon. But as of LM19 this is the only working applet for mouse control of the windows, which should mean that other users of Cinnamon Maximus will eventually find it and increase it's popularity.

**Comment by Sven71** [comment]
Unable to add title. The moment I do it the whole applet simply disappears from view. OS: Mint Cinnamon 19.1

**Comment by moretocome** [comment]
I am using it right now on two machines running LM19.1. I am using @Odyseus' version, and it works like a charm, so I suspect your problem is local, @Sven71

**Comment by mash-00** [comment]
awesome applet and should be definitely easier to find :-), thanks!

**Comment by mash-00** [comment]
hi @Odyseus ,

since you brought us this awesome applet back, I think what I am about to ask is best placed here.

since the update to (I believe due to the PR mentioned below) cinnamon 5.4 (though currently on 5.6.8) the maximize signal seems to fail.
I already did _some_ digging but since this is not my field of expertise at all I kind of got stuck.

I used Melange/Looking Glass Logs to check why this awesome applet stopped working and tried to fix it.
The log says: 
`No signal 'maximize' on object 'CinnamonWM'`

This seems to be related to this issue in the (popular) maximus extenstion: 
https://github.com/linuxmint/cinnamon-spices-extensions/issues/385

Seemingly solved by this PR already: 
https://github.com/linuxmint/cinnamon-spices-extensions/pull/392/files

When starting the applet as it is now (referring to the .zip you have uploaded) it crashes right away. 
When selecting "Show applet (active buttons-title-icon on this instance) only active window maximized" under its applets settings, it actually starts working somewhat (enable/disable 2,3 times..); buttons are displayed again and are functional. 
Only displaying them when the windows are maximized does not work and I think the window icon is not working corrently but that is not as important for the applet to work again I guess.

I think that this is the line (and maybe others as well) that is causing the issue:
`global.window_manager.connect("maximize", Lang.bind(this, this._windowChange));`

Replacing it with:
`global.window_manager.connect("size-change", Lang.bind(this, this._windowChange));`

does not seem to work out of the box though, so maybe also get_maximized() on activeWindow would need to change somehow with something like:
`change === Meta.SizeChange.MAXIMIZE`

I am not quite sure though how to get/pass "change" correctly though.. referring to the PR that solved the issue for the maximus ext.

Referring to the comment in the PR:
`// Cinnamon 5.4 requires using size-change instead of maximize and unmaximize`

This might be related as well but not 100% sure: 
https://github.com/linuxmint/cinnamon-spices-extensions/issues/282

Do you or someone have any hint for me to make this awesome applet work again on cinnamon 5.6.8, as I said I kind of got stuck and would highly appreciate any support or help fixing it for us.

thanks again & in advance

**Comment by Odyseus** [comment]
Hello, @mash-00.

I wish I could be of help, but I can't use newer versions of Cinnamon (for personal reasons that I explain [here](https://gitlab.com/Odyseus/CinnamonTools/-/issues/9#note_1284539783)).

I hope that someone else can help you. Good luck. :+1:

**Comment by Drugwash2** [comment]
I'll take a look at it.
Upon a quick change buttons are now shown in panel but window title is not. Needs some more fixes.
Could anyone provide exact details on what the applet should look and work like, just to avoid any confusion?
Will try and upload it to my repository if/when done.

**Comment by mash-00** [comment]
Hi @Odyseus , thanks and thanks for your quick reply - that is already more than I hoped for. Never change a running system I guess :-)!

Hi @Drugwash2 , awesome - thanks a lot :-)!

Frankly, I never saw the fully working applet (nor know anyone who did) - I only used the version @Odyseus fixed for us after some intense digging on the linux mint forums (https://forums.linuxmint.com/viewtopic.php?t=272206).
I just used the three buttons and icon of the app (show desktop function) that is currently focussed (icon:). Even the icon is not really needed from my POV but is an extra, keeping efforts to a minimum.

Maybe somebody else that knows more about it finds this post and can provide some more useful insights.

However, making an educated guess and providing at least some input, I assume that the title would be the title of the window that is currently focussed. What I believe it should do is basically moving the whole information of the "decorated window" (removed by Maximus when maximized) to the panel to save space, along some additional functions and info; e.g. additonal key-binding, show desktop on icon click and display options of this info like the max length of the title string, etc, which is especially great for notebooks.

The real issue that I attempted to fix/needs fixing is the checking of maximized windows, so that the control-buttons "move" to the panel only when a window is maximized instead of being statically displayed when focussing non-maximized windows (`global.window_manager.connect("unmaximize", Lang.bind(this, this._windowChange));`).

With that fix, I think it is useable again together with Maximus (awesome combination of applets with Smart Panel extention). Essentially, making the panel a smart window decoration for maximized windows, that feels natural and polished, while saving screen space.

Hopefully that helps a bit!

**Comment by Drugwash2** [comment]
OK, tried a quick fix and it seems to work.
However please note I do not have the maximus applet installed and therefore am not sure whether it behaves correctly when combined with it. Fingers crossed!

See **[here](https://github.com/Drugwash2/window-buttons-with-title2)** for v2.1.0.

**Comment by mash-00** [comment]
Cool and thanks again mate, highly appreciated :-)!

**Comment by DrBenana** [comment]
Hi, can someone provides another link to this applet? It shows only 404 when I click it.

**Comment by mash-00** [comment]
Hi @DrBenana ,
sure, [here](https://github.com/mash-00/window-buttons-with-title2). 
KR

**Comment by mz1193** [comment]
> Hi @DrBenana , sure, [here](https://github.com/mash-00/window-buttons-with-title2). KR

Hey mash, thanks for the update. I'm curious, is there any way to make this applet hide the in-app window buttons of CSD applications, such as gnome-system-monitor? It gets kind of cluttered ending up with two sets of window buttons when those are maximized. :)

**Comment by mash-00** [comment]
Hi @mz1193 ,

you will not like what I am about to say, but I will say it anyway :smiley:!

In short - no, [window-buttons-with-title2 ](https://github.com/mash-00/window-buttons-with-title2) is not capable of modifying the decoration/title bar of GNOME apps like gnome-system-monitor.

I take it that you already know the [Cinnamon Maximus](https://cinnamon-spices.linuxmint.com/extensions/view/73) extension. And since you are using Linux, tradeoffs should not be completely out of the question, right? Which, I guess, is true for all the OSes out there, not just Linux.

What you, me and likely many other Linux users are experiencing is what I call "inhomogeneous Linux desktop environment"(s), I think of it like this anyway. Maybe take a look at [window tiling managers on the arch wiki](https://wiki.archlinux.org/title/Comparison_of_tiling_window_managers) or searching for "top" lists:
https://www.tecmint.com/best-tiling-window-managers-for-linux/

I assume that you are on Cinnamon, for GNOME desktop environments this should work (not tested though): https://www.baeldung.com/linux/gnome-remove-title-bar

If you are looking for a _quick_ "solution" I'd  recommend _an_ alternative app, such _as_ [Stacer](https://oguzhaninan.github.io/Stacer-Web/).

- GitHub: https://github.com/oguzhaninan/Stacer
- Review by Chris Titus Tech: https://www.youtube.com/watch?v=MHcuqCzAhWM

I took a quick look at it prior to replying, having the xz 5.6.1 backdoor issue in mind (for the memes, _he uses arch btw_ lol - https://www.youtube.com/watch?v=s_WkMtEPsuE).

Even though Stacer seems to be recommended by the community and has a nice look - frankly, I find it way too powerful for my taste and how it nests itself into the system - just not my cup of tea.
I would like to point out that top and **[htop](https://itsfoss.com/use-htop/)** are on the other side of _the_ spectrum (light weight?), I use htop mostly - which I recommend even alongside apps like gnome-system-monitor, so you _can_ eat your cake and have it, too :grin:. Because [the CLI is amazingly beautiful](https://itsfoss.com/zsh-ubuntu/), isn't it.
More alternatives (just two of many web search results):
- https://itsfoss.com/linux-system-monitoring-tools/
- https://www.geeksmint.com/best-linux-system-monitoring-tools/

One might say its lazy, however, my take on this issue is even quicker and simpler than running alternative apps that might or might not support my window decoration of choice.

> ~~when~~ **if** those are maximized. :)

What I do is simply running it **just in windowed mode**, _unmaximized_. It works for me, but I rarely use apps like gnome-system-monitor, so this might not be a "solution" for you.

Luckily, there is something for flatpaks to use the system theme (fyi [Flatseal](https://community.linuxmint.com/software/view/com.github.tchx84.Flatseal)): https://itsfoss.com/flatpak-app-apply-theme/

Also, I will leave this link here, which I came across: https://www.reddit.com/r/linuxmint/comments/rgvu25/linux_mint_203_will_change_to_a_gnome_like_title/

KR

**Comment by mz1193** [comment]
> Hi @mz1193 ,
> 
> you will not like what I am about to say, but I will say it anyway 😃!
> 
> In short - no, [window-buttons-with-title2 ](https://github.com/mash-00/window-buttons-with-title2) is not capable of modifying the decoration/title bar of GNOME apps like gnome-system-monitor.
> 
> I take it that you already know the [Cinnamon Maximus](https://cinnamon-spices.linuxmint.com/extensions/view/73) extension. And since you are using Linux, tradeoffs should not be completely out of the question, right? Which, I guess, is true for all the OSes out there, not just Linux.
> 
> What you, me and likely many other Linux users are experiencing is what I call "inhomogeneous Linux desktop environment"(s), I think of it like this anyway. Maybe take a look at [window tiling managers on the arch wiki](https://wiki.archlinux.org/title/Comparison_of_tiling_window_managers) or searching for "top" lists: https://www.tecmint.com/best-tiling-window-managers-for-linux/
> 
> I assume that you are on Cinnamon, for GNOME desktop environments this should work (not tested though): https://www.baeldung.com/linux/gnome-remove-title-bar
> 
> If you are looking for a _quick_ "solution" I'd recommend _an_ alternative app, such _as_ [Stacer](https://oguzhaninan.github.io/Stacer-Web/).
> 
>     * GitHub: https://github.com/oguzhaninan/Stacer
> 
>     * Review by Chris Titus Tech: https://www.youtube.com/watch?v=MHcuqCzAhWM
> 
> 
> I took a quick look at it prior to replying, having the xz 5.6.1 backdoor issue in mind (for the memes, _he uses arch btw_ lol - https://www.youtube.com/watch?v=s_WkMtEPsuE).
> 
> Even though Stacer seems to be recommended by the community and has a nice look - frankly, I find it way too powerful for my taste and how it nests itself into the system - just not my cup of tea. I would like to point out that top and **[htop](https://itsfoss.com/use-htop/)** are on the other side of _the_ spectrum (light weight?), I use htop mostly - which I recommend even alongside apps like gnome-system-monitor, so you _can_ eat your cake and have it, too 😁. Because [the CLI is amazingly beautiful](https://itsfoss.com/zsh-ubuntu/), isn't it. More alternatives (just two of many web search results):
> 
>     * https://itsfoss.com/linux-system-monitoring-tools/
> 
>     * https://www.geeksmint.com/best-linux-system-monitoring-tools/
> 
> 
> One might say its lazy, however, my take on this issue is even quicker and simpler than running alternative apps that might or might not support my window decoration of choice.
> 
> > ~when~ **if** those are maximized. :)
> 
> What I do is simply running it **just in windowed mode**, _unmaximized_. It works for me, but I rarely use apps like gnome-system-monitor, so this might not be a "solution" for you.
> 
> Luckily, there is something for flatpaks to use the system theme (fyi [Flatseal](https://community.linuxmint.com/software/view/com.github.tchx84.Flatseal)): https://itsfoss.com/flatpak-app-apply-theme/
> 
> Also, I will leave this link here, which I came across: https://www.reddit.com/r/linuxmint/comments/rgvu25/linux_mint_203_will_change_to_a_gnome_like_title/
> 
> KR

Thank you so much for the detailed and thorough explanation. I really appreciate you taking the time to write it out and explain everything! I don't think I realized what a rabbit hole this whole topic actually is.

**Comment by mash-00** [comment]
Hi @mz1193 ,

looked a bit more into it, since this whole topic kind of makes me not so fast but more like furious and wanted to share the gem I found.
I like the Cinnamon DE a whole bunch, yet I am also facing these inconsistencies and it drives me crazy :smiley:.

This is the best solution I could find thus far on GitHub (992 KB as .tbz): [btop++](https://github.com/aristocratos/btop)
Setup of btop: https://lindevs.com/install-btop-on-ubuntu/

While btop is a terminal program ("inspired by htop and alike"), **it allows interaction using mouse _and_ keyboard input**, which I find very appealing quite frankly; a terminal GUI program :grin:. And since it is a terminal program ctrl+c works as well.

I use gnome-terminal, should work fine for terminator, kitty etc. as well (untested though).

Pass a command/text to gnome-terminal and launch it maximized from a Shell Script (.sh). Since I run the terminal windowed mostly, I need to add options to run it maximized.

Here is the cmd:
`gnome-terminal --window --maximize -- btop`

I like to do it the ".sh-way"; allow to run it as program but locking that Shell Script (read only). To achieve this you could either use chmod or right click on the .sh -> Properties -> Permissions.
Alternatively, one could simply add cmds directly into the app Keyboard -> Shortcuts -> Custom Shortcuts, otherwise add the .sh-path instead.

The learning curve is very steep (ignore the [_snap_](https://linuxmint-user-guide.readthedocs.io/en/latest/snap.html#backdoor-via-apt) section, I personally love this decision, in favor of flatpak, which made me try and move completely to LMUE in the first place and never looked back): https://docs.vultr.com/how-to-install-and-use-btop-on-ubuntu-20-04#usage

And yes, btop offers [themes](https://github.com/aristocratos/btop?tab=readme-ov-file#themes), here is the [overview of available themes](https://github.com/aristocratos/btop/tree/main/themes). If you have not cloned the repo download it as .zip (green "Code" dropdown) and only extract the themes folder, put them here: `$HOME/.config/btop/themes`
 It is very easy to change an existing theme and match whatever works best for your machine, just change the hex colors in the .theme files (and add the modified .themes in the themes folder, too).
To start tinkering, simply hit esc -> options while running btop, the default options OotB are nice already though.

A side note; I also liked [bashtop](https://github.com/aristocratos/bashtop), btop++ is bashtop re-written in C++ and therefore faster, I would have been fine with bashtop, too. When resizing the window (e.g. windowed/maximized) it takes bashtop a couple of seconds to re-draw - btop resizes instantly.

I see this not as a workaround anymore but rather an evolution to replace "modern" apps by "old school" programs or even classics, that can be used in a "modern fashion", that is how I like to think of it anyway.

KR

**Comment by mz1193** [comment]
> Hi @mz1193 ,
> 
> looked a bit more into it, since this whole topic kind of makes me not so fast but more like furious and wanted to share the gem I found. I like the Cinnamon DE a whole bunch, yet I am also facing these inconsistencies and it drives me crazy 😃.
> 
> This is the best solution I could find thus far on GitHub (992 KB as .tbz): [btop++](https://github.com/aristocratos/btop) Setup of btop: https://lindevs.com/install-btop-on-ubuntu/
> 
> While btop is a terminal program ("inspired by htop and alike"), **it allows interaction using mouse _and_ keyboard input**, which I find very appealing quite frankly; a terminal GUI program 😁. And since it is a terminal program ctrl+c works as well.
> 
> I use gnome-terminal, should work fine for terminator, kitty etc. as well (untested though).
> 
> Pass a command/text to gnome-terminal and launch it maximized from a Shell Script (.sh). Since I run the terminal windowed mostly, I need to add options to run it maximized.
> 
> Here is the cmd: `gnome-terminal --window --maximize -- btop`
> 
> I like to do it the ".sh-way"; allow to run it as program but locking that Shell Script (read only). To achieve this you could either use chmod or right click on the .sh -> Properties -> Permissions. Alternatively, one could simply add cmds directly into the app Keyboard -> Shortcuts -> Custom Shortcuts, otherwise add the .sh-path instead.
> 
> The learning curve is very steep (ignore the [_snap_](https://linuxmint-user-guide.readthedocs.io/en/latest/snap.html#backdoor-via-apt) section, I personally love this decision, in favor of flatpak, which made me try and move completely to LMUE in the first place and never looked back): https://docs.vultr.com/how-to-install-and-use-btop-on-ubuntu-20-04#usage
> 
> And yes, btop offers [themes](https://github.com/aristocratos/btop?tab=readme-ov-file#themes), here is the [overview of available themes](https://github.com/aristocratos/btop/tree/main/themes). If you have not cloned the repo download it as .zip (green "Code" dropdown) and only extract the themes folder, put them here: `$HOME/.config/btop/themes` It is very easy to change an existing theme and match whatever works best for your machine, just change the hex colors in the .theme files (and add the modified .themes in the themes folder, too). To start tinkering, simply hit esc -> options while running btop, the default options OotB are nice already though.
> 
> A side note; I also liked [bashtop](https://github.com/aristocratos/bashtop), btop++ is bashtop re-written in C++ and therefore faster, I would have been fine with bashtop, too. When resizing the window (e.g. windowed/maximized) it takes bashtop a couple of seconds to re-draw - btop resizes instantly.
> 
> I see this not as a workaround anymore but rather an evolution to replace "modern" apps by "old school" programs or even classics, that can be used in a "modern fashion", that is how I like to think of it anyway.
> 
> KR

This is extremely valuable information, thank you!
