### ISSUE TITLE
Icing App manager

### ISSUE THREAD

**Issue by ctfolmar** [linuxmint/cinnamon-spices-applets#1945]
```
 * Applet version/Build date (to be found in "About.." or in "metadata.json")
 * Cinnamon version (cinnamon --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of applet**
@

**Issue**
Opening a Libre Office file puts an icon in the applet, however after saving a document, when Office is closed, the icon remains but is no longer functional.  I have to restart Cinnamon to remove the icon.

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by jaszhix** [comment]
There are a lot of issues with LibreOffice that have been tracked. Issues should be filed at the [dedicated repo](https://github.com/jaszhix/icingtaskmanager/issues?utf8=%E2%9C%93&q=is%3Aissue+libreoffice), as stated in the [readme](https://github.com/linuxmint/cinnamon-spices-applets/blob/master/IcingTaskManager%40json/README.md). If you do file an issue there, please fill out the issue template, otherwise its less likely to get fixed.
