### ISSUE TITLE
Multi-Core System Monitor - problem with too much cores

### ISSUE THREAD

**Issue by Dzordzik** [linuxmint/cinnamon-spices-applets#2032]
Multi-Core System Monitor - sorry, but Iḿ total new in Linux

```
 * Applet version 1.8.7
 * Cinnamon version (cinnamon --version) don't know but Mint 19
 * Distribution - Mint 19
 * Graphics hardware *and* driver used gtx 1070, last ver of proprietary driver

**Issue**
Hi, my home workstartion have totally 88 CPU cores (dual CPU, 22 cores each, 44 w HT). Problem is, I see on 29" monitor only  around half of all my CPU cores. Possible to select somehow less space between rows with cores or show info in 2 colums? In my version of plugin I didn't seen anything like this. Your plugin is what I try to find very long time, for my 100% happyines you can add for every core color bar for load and at right side number with percentace load as is now and temperature? Similar like in this screenshot. Ideally with CPU model name? Similar like Core temp widget on Windows?
http://www.shadowsembrace.com/images/CoreTempCapture.PNG


Look on google how much peoples try to find Core Temp widget for Linux - not possible. Not exist any.

Thank you very much.

Jirka

**Comment by jaszhix** [comment]
> Hi, my home workstartion have totally 88 CPU cores (dual CPU, 22 cores each, 44 w HT). Problem is, I see on 29" monitor only  around half of all my CPU cores. Possible to select somehow less space between rows with cores or show info in 2 colums? In my version of plugin I didn't seen anything like this. Your plugin is what I try to find very long time, for my 100% happyines you can add for every core color bar for load and at right side number with percentace load as is now and temperature? Similar like in this screenshot. Ideally with CPU model name? Similar like Core temp widget on Windows?

Sorry, this extension was just not designed for this extreme edge case.

I agree there is a void in the Linux space for something like CPU-Z, but it shouldn't be running inside Cinnamon. Its just supposed to be a part of the panel, and there is a limit to how much data an applet can show for practical reasons. I suggest not using the applet and looking for more appropriate monitors for server hardware.

**Comment by Dzordzik** [comment]
Hi Jason, my workstations isn´t any extreme case. Many of my friends have new desktops with new AMD Threadripper where is 64 threads and in near future will be number of cores growth. You write about CPU-Z but I´m writing about Core temp app for Linux. I think super will be add to your util option to show only physical HW cores/all threads incl. HT cores. It divides number of rows to half. And if possible add to your util on same row as load percentage temp of this core. This will make your util much more usable. And ideally made it visible on desktop, not in cinnamon bar where it is too smal and not readable. Only in our BOINC team is around 800 users that are using Linux and try to solve same problem as I. Can check if possible to do it please? Please please :)

**Comment by jaszhix** [comment]
I'm running a Xeon with 14 cores/28 threads - on a 1440p display. The tooltip fills less than half of the monitor. This will also depend on how many disk and network devices are enabled. 

The trouble will be figuring out where in /proc I could find the HT info, so we know to divide them or not.  That adds I/O to the applet, which is already demanding on Cinnamon. Fetching hardware info would, too. Those are legitimate suggestions, but this issue came packed with both a bug report and a feature request. I think for the vast majority of users this will not be an issue, even with threadripper. No consumer CPU will have anywhere near 88 cores for the next few years.

**Comment by Dzordzik** [comment]
I understand you, but I think better will be add selection box for show load of cores as numbers or as load bar. Bar can be much thicker that number. And for analysis of cores load per CPU is much more usable to see it as bar instead as number. For fine tuning of CPU load you must see it graphically and in real time. With bars it is easy, with numbers not possible. BTW, looks like I find some bug, because when I open on my system settings menu, width of menu is wider than my monitor and I cannot resize it and I don´t see "Height" item in my settings. Think my pligin is in last version and on screenshots this item is presented. On my PC not. Why and for what it this item? This is height of what?
BTW: Is possible to show cores on multiple CPU divided to 2 groups? So all cores from CPU0 and all cores from CPU1 separately (some line as divider or so)? It will be much clearer to read. Think Linux use first half of cores from CPU0 and second half from CPU1. Right?

**Comment by jaszhix** [comment]
> BTW, looks like I find some bug, because when I open on my system settings menu, width of menu is wider than my monitor and I cannot resize it and I don´t see "Height" item in my settings. Think my pligin is in last version and on screenshots this item is presented. On my PC not. Why and for what it this item? This is height of what?

Are you talking about the panel or the extension's own settings? The multi-core applet only has width control, height is controlled by the panel. Screenshot might help here - from the original issue its not clear exactly what part of the applet is causing issues, I assumed the tooltip was clipping the screen.

> For fine tuning of CPU load you must see it graphically and in real time. With bars it is easy, with numbers not possible.

I think what you're wanting is a desklet - this would need to be a new extension to make it look and behave like the picture you provided.

> Is possible to show cores on multiple CPU divided to 2 groups? So all cores from CPU0 and all cores from CPU1 separately (some line as divider or so)? It will be much clearer to read. Think Linux use first half of cores from CPU0 and second half from CPU1. Right?

Feel free to open a feature request. When you open an issue its good practice to keep it focused on one thing, otherwise it becomes harder to understand what the problem/suggestion is when we're discussing four things at once. For bug reports, providing logs and screenshots of the applet helps, too.

**Comment by jaszhix** [comment]
Sorry I'm already maintaining a system monitor applet that is adequate for me. This issue is finished, if you would like to report any further bugs or feature requests please open separate issues that are focused on one thing, and provide everything requested in the issue template.
