### ISSUE TITLE
 [SpicesUpdate@claudiux] improvement suggestions

### ISSUE THREAD

**Issue by Mintulix** [linuxmint/cinnamon-spices-applets#2219]
Hey @claudiux,

two or three improvement suggestions:

1. Order in popup menu (left click on icon): current order is "Applets, Themes, Desklets, Extensions". I think themes is a bit misplaced, it should be on bottom/end like in the tabs.

2. The change of active or inactive spices update checks is realized with a slider, displayed is TRUE or FALSE. This looks a bit odd for non-programmers and in other languages than English.
Could this be made directly with checkboxes?

(3.) I don't know if it's a good idea, but sooner or later someone will have that suggestion, too: to update spices right in your applet.
However, it must be ensured that the already implemented mechanisms of Cinnamon are used, otherwise there could be problems if something should be changed there sometime.

Thank you for all other improvements since version 1.0!

**Comment by claudiux** [comment]
Hi @Mintulix,

1. This is fixed in #2218.
2. This will certainly fixed in Cinnamon 4.2 (look at https://github.com/linuxmint/Cinnamon/pull/8311) and cannot be resolved by the code of this applet.
3. This was rejected by the Cinnamon team (look at #2165).

Thank you for your participation in the improvement and translation of Spices Update!
