### ISSUE TITLE
stopwatch applet: The configuration panel doesn't allows to add multiple instances

### ISSUE THREAD

**Issue by a-bentofreire** [linuxmint/cinnamon-spices-applets#2349]
```
 * Applet  2.1.2
 * Cinnamon 4.0.9
 * Distro: Linux Mint 19.1 Tessa base: Ubuntu 18.04 bionic
 * Device-1: Intel Skylake GT2 [HD Graphics 520] vendor: Acer Incorporated ALI driver: i915 v: kernel bus ID: 00:02.0

.xsession-errors:
Cjs-Message: 11:33:48.837: JS LOG: [LookingGlass/info] Installing settings for stopwatch@pdcurtis
Cjs-Message: 11:33:48.838: JS LOG: [LookingGlass/info] Settings successfully installed for stopwatch@pdcurtis

glass.log: no relevant information
 ```

**Issue**
After I install, and added to the tray, I go to the configuration dialog box, but only displays the general settings for the applet. It doesn't allows me to add more instances, as shown on the image below:

![config-box](https://user-images.githubusercontent.com/7064913/53779777-741a9e80-3f3c-11e9-9b08-b840271150c9.png)

**Expected behaviour**
Allow to add multiple instances:
![Expected](https://cinnamon-spices.linuxmint.com/git/applets/stopwatch@pdcurtis/screenshot.png)

**Other information**

* Error displayed on applets panel: 
![error](https://user-images.githubusercontent.com/7064913/53780094-b1cbf700-3f3d-11e9-9938-765879e7dc12.png)

* My theme info:
![theme](https://user-images.githubusercontent.com/7064913/53780164-08d1cc00-3f3e-11e9-8df6-7350e2b26701.png)
png)

The xsession-errors contains more info but it can be from other sources:
```
Gtk-Message: 11:34:07.171: GtkDialog mapped without a transient parent. This is discouraged.
X protocol error:
<class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x062008e9), sequence_number = 43670, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x062008e9), sequence_number = 43671, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 65021943, sequence_number = 44635, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 65021943, sequence_number = 44636, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 65022434, sequence_number = 46107, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 65022434, sequence_number = 46108, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 65022536, sequence_number = 46830, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 65022536, sequence_number = 46831, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x07c0028f), sequence_number = 53386, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x07c0028f), sequence_number = 53387, major_opcode = 33, minor_opcode = 0
X protocol error:
```

**Comment by pdcurtis** [comment]
@a-bentofreire Sorry I took so long but you did not put me as author in the issue comment so I only found it by chance. Issues do not automatically get to the author, a poor feature of Github.

Extra instances can be added from the Applets in the Control Centre (The + at the bottom of Manage Tab). The latest versions of Cinnamon do not offer adding and removing within Configure dialogue from the right click menu. 

So what you are seeing is the expected behaviour and is Not an issue - it is a Feature of the new versions of Cinnamon. You reach the different instances from the arrows at the top. I agree that it is not such a convenient display but there is nothing I can do so can you please close the issue.

I however need to update the image in the description and will do so at my next update.

I am not sure why you got an error message, I have not been able to replicate it and there have been no other reports. Have you seen it again? If you do it should be a different issue.

**Comment by a-bentofreire** [comment]
Hi,
Thank you for the reply.
After mutter for a while, I reproduce the solution. 
Yes, it works but it's quite an awkward solution.

Regarding the error message, yes, I still see it using Cinnamon 4.0.10 which it's up to now the latest stable version. Cinnamon 4.2 is still in BETA. The stable version will be release soon.
