### ISSUE TITLE
IcingWindowSaver@json feature request

### ISSUE THREAD

**Issue by smurphos** [linuxmint/cinnamon-spices-applets#2352]
```
 * Applet version/Build date 2.0.0
 * Cinnamon version 4.0.9
 * Distribution - Mint 19.1

```
@jaszhix 

**Feature Request**

Hi Jazhix - any appetite to expand the feature set of this applet? 

I was unaware that is existed until a few days ago.

What would be nice are options to also 

1) Save and restore the window's workspace.
2) Launch any application windows on restore that were open at the point of saving that are not open at the point of restore.

**Comment by jaszhix** [comment]
Yeah, I actually have some changes I've been testing locally for a while, but haven't got around to committing - which is restoring  window stack order between restarts.

1. This is possible. Muffin also has a session restore feature that is currently disabled, I want to test that before doing any more extensive extension work in this area.
2. This can get tricky because Cinnamon can only preserve windows across reboots, not restarts, and it can't make too many assumptions. Still would be useful, but again I think we should dust off Muffin's forgotten session restorer and test it to see if it's worth salvaging.

**Comment by heyvoon** [comment]
Why this feature (applet) have been removed?! 
Would it be possible to consider adding this functionality in a future release of Cinnamon? I genuinely believe that this feature would greatly benefit many users and make Cinnamon even more user-friendly. Thank you for considering this request, and I am more than happy to collaborate or provide further feedback to support this effort.
