### ISSUE TITLE
weather@mockturtl: Makes system animations lag

### ISSUE THREAD

**Issue by monkeyboy537** [linuxmint/cinnamon-spices-applets#2437]
```
 * Applet version/Build date (to be found in "About.." or in "metadata.json")
 * Cinnamon version (cinnamon --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of applet**
@

**Issue**

Make Linux mint animations (some are not affected) go really laggy unless the applet updates, which does not update

**Steps to reproduce**

Add the weather spice to bar, then put system to sleep, wake up and wait, then it lags

**Expected behaviour**

It should update and not make mint animations lag

**Other information**
I don't know if this is gonna help you or not, but my computer does have a decent graphics card!
so it is not that, has graphic card drivers

**Comment by Gr3q** [comment]
Hello,
What version of cinnamon are you using, and what version of the applet are you using?

**Comment by rdlf4** [comment]
I'm on Linux Mint 19.1 (I know, it's older, but Vino breaks on older versions and my job depends on that) and I can relate to this bug.
Actually, it's even worse: Pressing the Win (or Super) button generates a lag: system animations freeze and if I'm playing a video, it also freezes before the menu comes up. The problem is, that doesn't happen just once. Every-single-time I press the button or click on Cinnamenu, after a 1.5s delay, the menu comes up. So we have the lag issue and also the fact that Cinnamenu ALWAYS takes some time to show up after requested by the user.

Cinnamon v4.0.10
Cinnamenu v4.1.5

Please let me know if there's some other info I can provide to help you further.

**Comment by monkeyboy537** [comment]
Sorry it took like a year to respond. I forgot about it like other things. I don’t have the Linux mint installation anymore but I discovered that it isn’t the applet that is doing it. Other Linux distros do have the same problem applet installed or not. Also found out Linux has poor sleep wake things anyway. I’m closing it because it isn’t a problem with the applet.
