### ISSUE TITLE
CinnVIIStarkMenu@NikoKrause: Linux Mint 19.2 Tina not compatible

### ISSUE THREAD

**Issue by ThunderCatBH** [linuxmint/cinnamon-spices-applets#2507]
```
 * Applet version/Build date (to be found in "About.." or in "metadata.json")
 * Cinnamon version (cinnamon --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of applet**
@

**Issue**

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by jimthedj65** [comment]
In my 19.2 looking glass I found the following 
rror t=2019-08-12T12:54:54Z [CinnVIIStarkMenu@NikoKrause]: Extension is not compatible with current Cinnamon version

warning t=2019-08-12T12:57:19Z [CinnamonDBus] [CinnVIIStarkMenu@NikoKrause] Unable to find UUID from SettingsManager - this is likely due to configuring settings from a removed xlet.

warning t=2019-08-12T12:57:26Z [CinnamonDBus] [CinnVIIStarkMenu@NikoKrause] Unable to find UUID from SettingsManager - this is likely due to configuring settings from a removed xlet.
