### ISSUE TITLE
Why have some Spices lost stars ???

### ISSUE THREAD

**Issue by claudiux** [linuxmint/cinnamon-spices-applets#2542]
**Issue**
Two of my applets have lost stars:

- [vpnLookOut@claudiux](https://cinnamon-spices.linuxmint.com/applets/view/305): -1 (from 8 to 7)
- [sound150@claudiux](https://cinnamon-spices.linuxmint.com/applets/view/306): -6!!! (from 7 to 1)

**Expected behaviour**
Respecting the work and efforts of the developers, do not remove any star anymore.

**Other information**
I'm working on a version of sound150@claudiux to make it fully compatible with Cinnamon 4.2. Seeing this loss of 6 stars, I think now to remove this applet.

**Comment by smurphos** [comment]
@claudiux I believe stars expire after 1 year, albeit it needs someone to give a star for the count to adjust down to reflect the expired stars. I don't really like this behaviour either, as I think the star system is relatively hard to discover for new users. In an ideal world I'd like end users to be able to give stars directly from the relevant Cinnamon settings modules, or a mechanism to be introduced to count downloads.

**Comment by claudiux** [comment]
@clefebvre @mtwebster @brownsr 
The Spices Update applet has just lost 5 stars (from 56 to 51). I'm furious and discouraged to continue to develop and improve any applet. Spices Update was in continuous development. I participated in the improvement of other Spices (even those of which I was not the author) and Cinnamon. I consider my work on Spices to be very poorly recognized and ask myself the question: why spend so much time doing it? Please modify the unsuitable algorithm which manages the Spices stars.

**Comment by Gr3q** [comment]
I don't have this string opinion about this, but I agree the algorithm is u unsuitable for its purpose like this.

At least it should be clear to show a total count and the count for the past year

**Comment by brownsr** [comment]
The rating system isn't perfect, but your contributions are very much
appreciated I can assure you. The purpose of the scoring cutoff after some
time is so that newer applets that become popular can climb the rankings.

Kind regards

Simon

**Comment by claudiux** [comment]
Thank you @brownsr.

I understand the need for more recent applets that become popular to be able to climb in the ranking, but this should not be done at the expense of already popular applets which are constantly improved by their author. There is no reason why they should be devalued. 

It is absolutely necessary to create a new, fairer algorithm, in agreement with the authors of Spices.

Kind regards

Claudiux

**Comment by clefebvre** [comment]
Let's review it. The reason it was like that was to give a chance for new applets to get some visibility and not have popular ones stay at the top even if their famed was ancestral.

I'll fetch the exact formula tomorrow so we can review it and discuss it here together.

**Comment by clefebvre** [comment]
OK, so it's calculated as follows:

`SELECT COUNT(*) WHERE FROM_UNIXTIME(timestamp) >= DATE_SUB(NOW(), INTERVAL 1 YEAR)'`

In other words, it's the number of likes not older than a year.

**Comment by clefebvre** [comment]
So, I think the biggest issue here is misunderstanding and the assumption that there was foul play. Now that we've cleared that, let's look at the formula and the issues it solves and the issues that it doesn't solve :)

Without a formula, if we just count likes without taking time in consideration, we let spices accumulate likes over time and slowly climb to altitudes it would take new applets months, years even to get to. You could have a spice that's been there 5 years, maybe popular at the start and not so much nowadays, nobody's really rating it much.. but after 5 years it's up there. Say you make a new applet everybody loves.. the best thing in town. We want to see that new applet at the top of the ranking, because what we care is to see what's popular right now, not what has been popular over the last 5 years.

Now, there's another problem that this formula doesn't solve... once somebody rated something he/she can't rate it anymore. The rating is getting older.. until eventually it passes the year limit and isn't counted anymore. The problem we have here is that a year only represents an arbitrary measure of time, not changes in popularity per se. If I rated something 5 years ago, I might still like it.. I might not, who knows? We can't assume I still do, but we can't also assume I no longer do and chances are I still do.

So if I look at a 5 year old applet with a rating of 50, and a brand new applet with a rating of 10.... I know precisely how popular that new applet is right now, but I can't really say if it's more or less popular than the old one... because in these ratings, some of them are still very relevant, but some no longer are.

I don't really have a better formula or an idea on how to improve this. Here are the issues at play anyway. Let's try to address them better.

Do you guys have ideas on how we could do? Maybe this was done and thought about in other places around the Web with rating systems?

**Comment by clefebvre** [comment]
Some data might help. Here's the top 10 without formula:

```
weather@mockturtl                     |      103 
IcingTaskManager@json             |       66 
SpicesUpdate@claudiux             |       57 
CinnVIIStarkMenu@NikoKrause |       50 
Cinnamenu@json                        |       49 
temperature@fevimu                   |       47 
multicore-sys-monitor@ccadeptic23 | 41 
placesCenter@scollins                |       31 
windowlist@cobinja.de                |       29 
collapsible-systray@feuerfuchs.eu |    28 
```

**Comment by clefebvre** [comment]
IcingTaskManager@json is a good example (and a bad one also since it was removed). It became really popular because it brought something that people wanted and which wasn't in Cinnamon core. When it was integrated as GWL, some of the IcingTaskManager were left out, so for a while we had GWL which had most of what people wanted, but we also still had ITM which brought some of the niche features GWL didn't have and that some ITM users had grown found of.

There's no doubt ITM was more popular before the introduction of GWL than after, but without a formula past glory does not fade. If you imagine ITM still being maintained nowadays, now that we've got GWL, it wouldn't be as relevant to users as weather or spicesupdate which features are lacking in Cinnamon core.

I think that illustrates the need to consider time in the popularity ranking. We might need to consider more than time of course, but we do need to consider it.

**Comment by Gr3q** [comment]
In reality we have 2 data points here what we cannot mix without losing information.

Currently an applet _popularity_ is shown for the last year and simple labelled as "Stars".
The other one is _total votes_ what is not shown anywhere but can still give valuable information.

Explicitly declaring the logic behind the Star system next to the starts with a tooltip or footnote or sth would be an improvement and probably lessen @claudiux 's frustration even if the formula is not changed.

**Comment by clefebvre** [comment]
@Gr3q yes that's a good point too.

**Comment by clefebvre** [comment]
To continue my illustration, here's the top 10 with the current formula:

```
+-----------------------------------+----------+
| uuid                              | count(*) |
+-----------------------------------+----------+
| SpicesUpdate@claudiux             |       51 |
| weather@mockturtl                 |       35 |
| temperature@fevimu                |       18 |
| Cinnamenu@json                    |       17 |
| CinnVIIStarkMenu@NikoKrause       |       16 |
| collapsible-systray@feuerfuchs.eu |       15 |
| qredshift@quintao                 |       13 |
| multicore-sys-monitor@ccadeptic23 |       11 |
| sysmonitor@orcus                  |       11 |
| redshift@marvel4u                 |       11 |
+-----------------------------------+----------+
```
ITM's ranking is 4 (compared to 66 without the formula).

**Comment by Gr3q** [comment]
If a Star is not considered from an user anymore (older than one year, currently), add the ability to vote again for that user. (It is possible that this is implemented already, I simply don't know)

I would be happy with just this and providing information on the website.

**Comment by clefebvre** [comment]
I can confirm that at the moment, you can't re-like or unlike something you liked already.

**Comment by claudiux** [comment]
I have a solution, a bit complex to implement.

1. Add `Github account` in `System settings - > Accounts`.
2. In the Download tab of System settings - > Applets (or Desklets...) the star of each applet appears filled if the user has already rated the one during the last 365 days, greyed else.
3. When the user clicks on a star, its status change if the user has a registered Github account (else `System settings - > Accounts -> Github` will be opened).

Yes, a bit complex to implement, but more user-friendly and allowing the user to remove its star.

**Comment by collinss** [comment]
@clefebvre Just curious, is there a way to track the number of downloads by time?

**Comment by smurphos** [comment]
Could stars be displayed on the Spices website and in the relevant settings module as two figures, one for 'Lifetime' and one for 'Last 12 months'?

It would be nice if stars could be awarded from within Cinnamon as outlined by @claudiux.

**Comment by NikoKrause** [comment]
Maybe rating for a certain Cinnamon version would work?

As mentioned there are spices, which once were popular, but in the meantime they are unmaintained or broken, so becoming less popular. 

Lets play around with a little idea.
1. It's May 5th 2020 and Cinnamon 4.6 releases.
2. You go on cinnamon spices website and have a dropdown menu, where you can select you Cinnamon version. There's a new entry for Cinnamon 4.6.
3. The website shows only those spices, which were updated AFTER the release of Cinnamon 4.6. So at first the page will be empty and just say: "No updated spices for Cinnamon 4.6" available.
4. Once the maintainer or someone else pushes an update, the spice will show up with 0 stars.
5. A user, who already liked the spice for Cinnamon 4.4, would have the chance to like it for 4.6, without affecting his rating for Cinnamon 4.4.

I know it would be a lot of work. And there are probably better ideas. Just adding some input to think about.

**Comment by icarter09** [comment]
@NikoKrause i like the idea of displaying data based upon Cinnamon version.

I think a mixture of several options might be a good solution. Maybe the Spices page should have several columns that each list Spices by a different priority. List the top 10 by "most downloads", "highest star", have a column for the last 3 Cinnamon versions as well. This would provide a user with several points of data for all the given Spices. 

Another idea would be to only have a hard lock of one month's time or one week's time for when a user can change a rating. Once that time period has elapsed, they could then change the rating.

**Comment by Padre2** [comment]
@ claudiux  I just clicked to add a star to an applet and expected the number to increase by 1, but it decreased by two! Why?

**Comment by claudiux** [comment]
@Padre2 Thank you.

How many users will wonder why the score for this applet is declining?

**Comment by sphh** [comment]
I read this discussion with interest …

May I suggest another solution: We could display the mean rating, i.e. the total number of stars given divided by the age of the applet (scaled to a suitable size).

If newer ratings should be favoured, a weighted mean could be used. For example the weighting function could be `(suitable constant)/(days between the star was given to today)` (note, that this simple formula will favour a star given recently probably too much, so `(suitable constant)/sqrt(age of star)` might work better, but you can use any weighting function you deem suitable).

But in the end we have to admit, that _any_ rating system will be somehow unfair (just see the discussion about the different voting systems in the political world!)

**Comment by FranklinYu** [comment]
> I'm furious and discouraged to continue to develop and improve any applet.

Please don’t be. Your [CPU Temperature Indicator](https://cinnamon-spices.linuxmint.com/applets/view/106) helped several of my friends with their laptops.

> Could stars be displayed on the Spices website and in the relevant settings module as two figures, one for 'Lifetime' and one for 'Last 12 months'?

I like this idea of “more than one scores”. The idea is popular among other package registries; for example, https://www.npmjs.com has three metrics: popularity, quality, and maintenance.

**Comment by claudiux** [comment]
Any news on this issue?

**Comment by clefebvre** [comment]
Sorry for the delay @claudiux.

There are many good points in this discussion and I agree that no rating system is perfect, it's always somewhat arbitrary. I want to keep things simple but I see the point in counting past success.

Here what was done:

- A "recent" like is still a like which is less than a year old, that didn't change.
- Instead of only counting recent likes, the score is now made of "all likes" + "recent likes". In other words, we count everything but recent likes count double.
- Instead of just showing you whether you liked something or not, we now show you whether you liked it recently, a while ago or not at all.
- Users can like spices they liked in the past (they couldn't before). This refreshes the timestamp of the like.
- Tooltips explain recent likes count double, and users are encouraged to refresh old likes to boost the spice score.

With these changes things are a little more explicit, new spices can still get to the top but old ones don't see their past likes wiped like it happened in the past.

I hope you like the changes, sorry it took so long to implement these changes.

**Comment by NikoKrause** [comment]
The number of likes still can decrease. If an applet gets 50 likes today, you'll see them doubled, so 100 likes. If noone likes it anymore, the count decreases after a year to 50. It just won't decrease to 0 anymore.

**Comment by claudiux** [comment]
It seems fairer to me. The weather@mockturtl applet always deserved the first place. And users whose votes were previously forgotten without being able to vote again can now do so.

Well done and thank you!

**Comment by SebastJava** [comment]
@claudiux

> How many users will wonder why the score for this applet is declining?

I had started to think something was wrong with my coffee ! Here is my story:
[CinnamonSpices > Applets: Liked it, score went down !?](https://forums.linuxmint.com/viewtopic.php?f=90&t=365334)
