### ISSUE TITLE
weather@mockturtl: No translation of weather conditions

### ISSUE THREAD

**Issue by Bundy01** [linuxmint/cinnamon-spices-applets#2603]
```
 * Applet version/Build date (to be found in "About.." or in "metadata.json"): **2.3.0**
 * Cinnamon version (cinnamon --version): **4.2.4-2**
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): **Arch**
 * Graphics hardware *and* driver used: **Intel 4th Gen Core Processor**
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of applet**
@mockturtl

**Issue**
The weather conditions are not translated into my language as well as 'Today' and 'Tomorrow'.
Also a strange behavior if I choose the abbreviated conditions in the parameters.

![weather.png](https://i.postimg.cc/ZYGGLc6J/weather.png)

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by Gr3q** [comment]
Hello, can you paste the output of this command here:
```cat /etc/locale.conf ```
So I know the exact locale you are using. Just in case.

Today and Tomorrow is not translated to French (and languages) yet so that is known. 
Are "Aujourd'hui" and "Demain" correct words for them?

I presume you are using DarkSky. Found the bug in what was causing not getting translations from them.

Also, the weird text is the whole french translation file...I guess that happens when an empty string gets translated (another bug).

Fix Opened: https://github.com/linuxmint/cinnamon-spices-applets/pull/2606

**Comment by Bundy01** [comment]
Hello,

```
 cat /etc/locale.conf 
LANG=fr_FR.UTF-8
```

>  Are "Aujourd'hui" and "Demain" correct words for them?

It's the correct words in French.

I do effectively use DarkSky.
Regards.

**Comment by Bundy01** [comment]
I arrived after the battle:)
The PR resolves this issue as I close it.
Thanks.
