### ISSUE TITLE
SpicesUpdate@claudiux: Almost daily updates

### ISSUE THREAD

**Issue by Fabian42** [linuxmint/cinnamon-spices-applets#2610]
```
 * Applet version/Build date: 4.2.0
 * Cinnamon version: 3.2.7
 * Distribution: Debian 9.11
 ```

**Notify author of applet**
@claudiux 

**Issue**

Almost every day Spices Update notifies me of an update for itself. The applets menu does indeed let me update the applet, but the version number doesn't change, there is nothing new in the changelog, I see no different functionality and I generally doubt that a relatively simple applet like this needs daily updates anyway. So I assume that this is a bug, that the versions are indeed identical.

**Comment by brownsr** [comment]
There are quite a few translation changes coming through.

Regards

Simon

**Comment by acornforth** [comment]
I have also been experiencing this. It seems a little incongruous that this applet, which is supposed to make it _more_ convenient to update spices, now nags me nearly every day to update itself.
Given the purpose of this module, it seems like it might be a better strategy to accumulate the new translations and release an update once a week ?

Maybe it's different for users with dozens of spices installed, the likelihood of an update being needed every day would certainly increase, but for most of us, we see a spice update maybe once in a week or two. Updates to this spice should not be so frequent that 90% of the time this is the only spice to be updated !

**Comment by acornforth** [comment]
@Fabian42 i have found a workaround to the annoying updates 
![spices workaround](https://user-images.githubusercontent.com/4586381/66192149-c4e7a680-e687-11e9-8f35-bdf907687149.png)

**Comment by Fabian42** [comment]
Where do I find that? My applet menu looks completely different.
[image: image.png]

**Comment by claudiux** [comment]
@Fabian42 This menu appears only for Cinnamon 4.2 and you have Cinnamon 3.2. See https://cinnamon-spices.linuxmint.com/applets/view/309, please.

@Fabian42 and @acornforth Some users require improvements ; translators update .po files (many thanks to them!) Question : Should I make the improvements you require, which will generate new updates, or do not do so that you will not be bothered by these updates?

**Comment by Fabian42** [comment]
I didn't say you should never update the applet, I say that you should bundle changes. Nobody else actually releases daily, except if the deployment process is automated (which it isn't, every single user gets a notification and every single user needs to manually click to update the applet. Or they get annoyed with the notification on every reboot.

**Comment by claudiux** [comment]
@Fabian42 You can choose, in the General tab of the settings of this applet, not to send a notification. Thus, Spices Update will work as mintupdate, only changing the color of its icon when updates are available.

**Comment by acornforth** [comment]
that is how I have mine configured... unfortunately because the applet itself gI've no more indication about which applet needs an update...iit then required several cluck to open up the applet manager and discover that the only applet needing an update is this one...
i'm with Fabian here... 
I wouldn't want to deprive anyone of a much needed update... 
I also don't think a weekly release cycle for new translations would be too out of order this would still be faster than just about any spice in this repo..i am simply suggesting you pick a release cycle more in alignment with the purpose of the applet.... which is more than just to update itself every day.

**Comment by acornforth** [comment]
to clarify...i would still want to check for updates daily or hourly.... I just don't want this applet to be the only one I see listed 90 percent of the time

**Comment by acornforth** [comment]
perhaps being able to set how often to check for updates on a per applet basis....
could be a long term solution to please everyone...
or have a special setting for this applet to only check for update once a week? those waiting for fixes would still be able to update manually of course !

**Comment by claudiux** [comment]
@acornforth 
To know which Spices need an update, hover over the Spices Update icon with your mouse.

Translations are needed by many people. Out of respect for non-English speakers, it is good that these translations become available quickly.

I will not make an exception for my own applet in the treatment of Spices.

In addition, this would cause a new update of Spices Update ... you do not want anymore.
