### ISSUE TITLE
weather@mockturtl - TCP connection stays in CLOSE_WAIT

### ISSUE THREAD

**Issue by Mintulix** [linuxmint/cinnamon-spices-applets#2874]
@Gr3q 

Check the connection state with
lsof -i

During and after updating weather data the TCP state is ESTABLISHED, after a few seconds it changes to CLOSE_WAIT. So far ok, but it stays there "forever".

Shouldn't the connection be closed until the next refresh in x (e.g. 30) minutes?

**Comment by Gr3q** [comment]
@Mintulix There are possibly 2 issues here, assuming you are talking about the connection ip-api.com.

First (and this is the main issue), it seems the connection to ip-api.com does not immediately closes on request completion, it just hangs there. 

Now this can be caused by the applet (maybe I use the call improperly, I will double check), the underlying library I'm using or their end, or the combination of some of this. I know the connection is closed properly when I curl to the url.

Second, on my system the connection times out after 1 minute and it is dropped. This means the behavior you see is at least specific to your system. But the route cause is the first issue.

I will look into further when I will have time.

**Comment by Mintulix** [comment]
Thanks for the info.
I use the latest LM 19.3 with all updates and nearly no special installs.
There are only 2 connections hanging in CLOSE_WAIT - this weather applet and the weather desklet bbcwx@oak-wood.co.uk. All other connections are closed properly.
I don't know anything about TCP connections, just saw there is a constant download stream (~120 B/s) from these two spices.
If you think this should be changed/fixed, thanks in advance and take your time.

**Comment by Gr3q** [comment]
@Mintulix The issue is closed, but please let me know if the issue is gone or still there.

**Comment by Mintulix** [comment]
@Gr3q Works great, thanks a lot! I managed to provide your fix for the weather desklet bbcwx@oak-wood.co.uk also (https://github.com/linuxmint/cinnamon-spices-desklets/pull/556).
