### ISSUE TITLE
[temperature@fevimu] log message bug.

### ISSUE THREAD

**Issue by fredcw** [linuxmint/cinnamon-spices-applets#3107]
```

 * Cinnamon version 4.4 & 4.6
 * Distribution - Manjaro cinnamon (but not Linux Mint)
 
 ```

**Issue**
Not really much of a problem but message is being posted to ~/.xsession-errors about every 2 seconds so it builds up after a while:
"Cinnamon warning: Log level 128: posix_spawn avoided (automatic reaping requested) (fd close requested)"

Happens in manjaro but not linux mint.

e.g.: https://forum.manjaro.org/t/cinnamon-warning-log-level-128-posix-spawn-avoided-fd-close-requested/89703

**Comment by fredcw** [comment]
@claudiux Sorry, notified wrong person in original comment

**Comment by claudiux** [comment]
Hi @fredcw,

This is not an error message but a warning message, due to the used version of GLib.

This kind of message appears every time a command like ```GLib.spawn_command_line_async()``` or ```GLib.spawn_command_line_sync()``` (or its equivalent from `/usr/share/cinnamon/js/misc/util.js`) is used.

This discussion provides more details on this issue: https://gitlab.gnome.org/GNOME/glib/-/merge_requests/337

This applet uses this kind of command to execute `sensors` every time the display must be refreshed (the delay is configurable in settings).

To solve this problem, level 128 messages should be ignored by Cinnamon using `GLib.log_set_handler()`. Is it possible / desirable, @clefebvre ?
