### ISSUE TITLE
weather@mockturtl: RangeError: Invalid language tag: c

### ISSUE THREAD

**Issue by t3pfaffe** [linuxmint/cinnamon-spices-applets#3115]
```
 * Applet version/Build date: Version 2.6.2 (2020-07-12 15:43:30)
 * Arch, Kernel 5.4.5
 * NVIDIA 44x
 * Cinnamon Log:
> info t=2020-07-12T16:44:13Z Reloading applet: weather@mockturtl/17
> info t=2020-07-12T16:44:13Z [weather@mockturtl#17]: Removing applet instance...
> info t=2020-07-12T16:44:13Z Loaded applet weather@mockturtl in 106 ms
> error t=2020-07-12T16:44:14Z [weather@mockturtl#17]: DisplayWeatherError: RangeError: invalid language tag: c

 ```

**Notify author of applet**
@mockturtl 

**Issue**
Unable to load weather data, tried manual, non-manual, and default "London, UK" locations. Everything else default.

**Steps to reproduce**
Fresh arch/cinnamon install with weather applet

**Expected behaviour**
Weather works and displays data. 

**Other information**
Previously working on same network but different distribution, so I don't believe this to be a LAN issue. Persists between reboots.
![image](https://user-images.githubusercontent.com/16065962/87256462-d785dc00-c460-11ea-85b8-d813f2113c0b.png)

**Comment by Gr3q** [comment]
I came across this issue yesterday in the Linux Mint installation media. Your locale is still on the default, ```C``` instead of something else, like ```en_US.utf8```.

I admit the applet should handle this error better, what i will fix.

In the meantime you should set up localisation in your install correctly, as in the [Arch Linux Installation guide](https://wiki.archlinux.org/index.php/Installation_guide#Localization).

**Comment by t3pfaffe** [comment]
That is the correct solution, thanks!
