### ISSUE TITLE
cinnamenu@json - favorites with session buttons on top or bottom - cosmetic issue.

### ISSUE THREAD

**Issue by smurphos** [linuxmint/cinnamon-spices-applets#3177]
```
 * Applet version/Build date 4.3 (2020-08-08 18:36:44)
 * Cinnamon version 4.6.6
 * Distribution - Min 20
 ```

**Notify author of applet**
@fredcw 

**Issue**

In List view with the session buttons on top or bottom and favorites added to the session buttons the list-view menu-applications-inner-box doesn't extend it's width to fill the available space crated by including the favorite buttons with the session buttons.  It looks OKish in most themes until a category that needs a scrollbar is invoked. It looks plain bad for themes that have styling that makes it clear the actor is a box.

The issue can also affect grid view, if the user sets 3 columns and has a lot of favorites, but is more likely to be seen in list view.

**Steps to reproduce**

Set Cinnamenu to list view with Session Buttons on the Bottom or the Top, and set to include favorites with the session buttons.

**Expected behaviour**

menu-applications-inner-box should fill the available space.

**Other information**

With Mint-Y-Dark - note the placement of the scrollbar
![2020-08-09_05-34](https://user-images.githubusercontent.com/29017677/89725000-4293e580-da02-11ea-840d-53ef7c84fc81.png)

With Cinnamox-Rhino
![2020-08-09_05-34_1](https://user-images.githubusercontent.com/29017677/89725006-5a6b6980-da02-11ea-9dc4-ac1c967dd261.png)

**Comment by fredcw** [comment]
@smurphos I was wondering what to do about this problem. I was thinking that an extra wide apps list would also look a bit odd but it's probably better than a blank space. I'll try and fix this for the next update.
Did you notice the google search? I need to change it to a better icon and I've also implemented a calculator (next update) which is better than the search provider one. I never really liked the idea of the search providers because downloading them from github and installing them (while easy for you and me) is a bit much for the average user I think. It would be fine if they were installed with cinnamon by default but since they're not, I think that having them (or at least some of them) built in to cinnamenu is the better option. Also the enabling/disabling search providers should be implemented in cinnamon settings rather than in each menu so that they apply in whichever menu you use. In any case the search providers seem like an abandoned/unfinished project to me.

**Comment by smurphos** [comment]
Hi,

Maybe make the min-width of the box end-user configurable, which might save some coding complications. If users get as far into the config to set these options in the first place I'm sure they will realise they can then tweak the width to make things look good. In grid view they can either add more columns or increase the icon size already,

I think you are right regarding search providers - if ever I got it together enough  to write an applet / extension from scratch one potential project I had in mind was a search-provider manager to provide a GUI for installing and activating them. 

If you are going to build them into Cinnamenu I would give the users options to enable / disable them individually. You can guarantee that someone somewhere will freakout at being encouraged to use google search in the menu without being able to turn it off.

I use this icon for my google search provider although I don't think there's anything wrong with the G - it's clear what it is
![icon](https://user-images.githubusercontent.com/29017677/89727367-fbb2e980-da1b-11ea-975a-f1fc72fdcebe.png)
