### ISSUE TITLE
[Feature Request] for calendar@ccprog

### ISSUE THREAD

**Issue by Bundy01** [linuxmint/cinnamon-spices-applets#3296]
**Notify author of applet**
@ccprog 

Hi,

Would it be possible to create events using the css variable `calendar-day-with-events` in the applet?

For example by double-clicking on a date or right-clicking. With an option 'single event', 'repeat every month' or 'once a year'. The text of the created event would be readable by putting the mouse on the date as for public holidays.

Regards.

**Comment by ccprog** [comment]
This is a decidedly uncomfortable case. The applet needs to work independently of any theme, so it must not contain any CSS class that is not part of Cinnamon itself. `calendar-day-with-events` formally fullfills this requirement, it is defined in the default [cinnamon.css](https://github.com/linuxmint/cinnamon/blob/master/data/theme/cinnamon.css). 

But the existing styles, in existing themes, including the standard themes, do not include usable styles for this class. Please compare the above mentioned issue for further details.

For now, I see no workable way to leverage your idea, which I otherwise find compelling.

**Comment by Bundy01** [comment]
Okay,

if I understand correctly the idea is not viable despite the variable in the cinnamon theme.
Even if you add the variable in the 'stylesheet.css' file of the applet for themes that don't have `calendar-day-with-events`?
