### ISSUE TITLE
hwmonitor@sylfurd - Breaks Cinnamon 4.8

### ISSUE THREAD

**Issue by kelebek333** [linuxmint/cinnamon-spices-applets#3350]
```
 * hwmonitor@sylfurd / Version 1.3.1 (2020-06-01 23:48:17)
 * Cinnamon version : Cinnamon 4.8
 * Distribution : Linux Mint 20.x
 * GPU/Driver: Nvidia/340.108
 * xsession-errors: https://paste2.org/AKz5C9IM

 ```

**Issue**

Graphical hardware monitor (hwmonitor@sylfurd) breaks Cinnamon 4.8.

**Steps to reproduce**

Install and add Graphical hardware monitor to Cinnamon 4.8.

**Expected behaviour**

Applet should add to panel.

@Hultan

**Comment by Hultan** [comment]
Can you try and edit the file:

```/home/per/.local/share/cinnamon/applets/hwmonitor@sylfurd/3.8/providers.js```

and add the line:

```let info;```

before the while-statement at line 126? I didn't write this part of the code, so I am unsure about this.

**Comment by kelebek333** [comment]
I wrote Cinnamon version wrong, actually it would  be Cinnamon 4.8.

I also noticed that the iisue related is with Net (in) and Net (out) section. If I turn off Net (in) and Net (out) section,  applet works fine and Cinnamon is not crash.

**Comment by edwardzhxi** [comment]
yeah, found the same problem
turned off Net, working fine now
`Kernel: 5.10.2-051002-generic x86_64 bits: 64 Desktop: Cinnamon 4.8.3 Distro: Linux Mint 20.1 Ulyssa`

**Comment by Hultan** [comment]
Looking at the Cinnamon log file @kelebek333 sent in, I believe the error occurs on line 128 in providers.js. That is in the catch section of a try/catch statement, and it is most likely in the catch section because you don't have **gtop** installed. 

<----------------
**[email protected]/home/user/.local/share/cinnamon/applets/[email protected]/3.8/providers.js:128:31**
[email protected]/home/user/.local/share/cinnamon/applets/[email protected]/3.8/applet.js:216:34
[email protected]/home/user/.local/share/cinnamon/applets/[email protected]/3.8/applet.js:170:14
[email protected]/home/user/.local/share/cinnamon/applets/[email protected]/3.8/applet.js:70:10
[email protected]/home/user/.local/share/cinnamon/applets/[email protected]/3.8/applet.js:492:12
[email protected]/usr/share/cinnamon/js/ui/appletManager.js:582:25
[email protected]/usr/share/cinnamon/js/ui/appletManager.js:357:34
[email protected]/usr/share/cinnamon/js/ui/appletManager.js:95:14
_init/<@/usr/share/cinnamon/js/ui/extension.js:276:32
---------------->

The solution I suggested above (https://github.com/linuxmint/cinnamon-spices-applets/issues/3350#issuecomment-739328067) was an attempt to fix the catch code, that catch-code has probably never been tested before, but to avoid going  in to the catch section in the first place, by making sure that you have **gtop** installed, is most likely a better solution.

I am not 100% sure that this is the error, since I can't reproduce the problem on my machine. So I would make sure that **gtop** is installed first, and if that doesn't help, try the solution mentioned above (https://github.com/linuxmint/cinnamon-spices-applets/issues/3350#issuecomment-739328067) . As I said above, I did not write this code myself, so I am not sure about any of this.

Either way, let me know how that goes....

See requirements section in the readme:

https://cinnamon-spices.linuxmint.com/applets/view/12

**Requirements**

Graphical Hardware Monitor requires the **Gtop** and **GUdev** packages to collect system information. It might already be installed on your system, but if the applet or graph is not shown, you might need to install the packages manually.

**Debian/Ubuntu/Mint**: install the packages gir1.2-gtop-2.0 and gir1.2-gudev-1.0
**Fedora**: install the package libgtop2-devel and libgudev
**Arch/Manjaro**: install the package libgtop and libgudev

**Comment by kelebek333** [comment]
Hi @Hultan ,

gir1.2-gtop-2.0 and gir1.2-gudev-1.0 already installed. I add **_let info;_** line to providers.js file.

Now, network options is added to panel and then cinnamon crashes again. Can following outputs give clues related the issue?

```
Cjs-Message: 00:45:09.234: JS LOG: Unknown network device type, is 14
**
Cjs:ERROR:../gi/function.cpp:1063:void uninit_cached_function_data(Function*): assertion failed: (function->info && "Don't know how to free cache without GI info")
```

**Comment by Panther505** [comment]
I am seeing a similar crash on 4.8.3 on Fedora 33.  I verified that I have the 2 required packages installed. 

Error in the .xsession-errors file is the following:
Cjs-Message: 09:28:03.711: JS LOG: [LookingGlass/error] 
[hwmonitor@sylfurd]: Applet hwmonitor@sylfurd: Could not create applet object.
[hwmonitor@sylfurd]: Error importing applet.js from hwmonitor@sylfurd
Cjs-Message: 09:28:03.712: JS LOG: [LookingGlass/trace] 

Any thoughts/places to looks/suggestions would be appreciated. 

Version 1.3.1 (2020-06-01 21:48:17)

**Comment by kelebek333** [comment]
This issue solved by latest CJS update.

**Comment by kelebek333** [comment]
Hi @Hultan ,

If the applet is loaded from scratch, there is a issue adding to the panel, but Cinnamon does not crash. I hadn't tried this before, I had enabled network options in already added applet to the panel. For this reason, I realized that the previous feedback was missing. If you add `let info;` line to **providers.js** file, it also solves the issue of adding it to the panel from scratch.
