### ISSUE TITLE
Repo improvement: Add an ISSUE_TEMPLATE.md file

### ISSUE THREAD

**Issue by jaszhix** [linuxmint/cinnamon-spices-applets#34]
Adding an [issue template](https://help.github.com/articles/creating-an-issue-template-for-your-repository/) will give bug reports more structure. We can remind the user to list the applet's name/uuid, to mention the author so they get notified, and maybe pastebin log files which can save time. I already have this setup on one of my applet's repos and its saved me time not asking the same questions on every issue.

**Comment by NikoKrause** [comment]
I think we could add a CONTRIBUTING file, which says:
# Reporting Bugs

It's important to use a proper title when opening new issues. The title must be in the format `spice name: simple description of the problem.`

Issues that don't follow this format will be closed.

https://help.github.com/articles/setting-guidelines-for-repository-contributors/


And add a Issue/pull request template, which reminds the user to notify the author:
@AppletAuthor

**Comment by NikoKrause** [comment]
I added a CONTRIBUTING template. It works for issues. Haven't tried with pull requests. Let me know.

@JosephMcc
Do you think, we should also add an Issue/pull request template, which reminds the user to notify the author:
@AppletAuthor

You can try the CONTRIBUTING template and let me know, if we should add this to the other spices repos.

**Comment by JosephMcc** [comment]
@NikoKrause You can add one for PR's. I haven't ever tried them. The best way to enforce it is to quit merging PR's that don't follow the commit message rules we lay out. You can ask for them to be fixed and only merge once they are.

With all the applets in one large repo some sort of organization should be enforced, imho.

**Comment by Odyseus** [comment]
Hello, everybody.

@NikoKrause: The CONTRIBUTING.md file isn't a template *per se*. The CONTRIBUTING.md file is a file that should contain contribution guidelines. The *real template* for pull requests is a file called [PULL_REQUEST_TEMPLATE.md](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/).

The PULL_REQUEST_TEMPLATE.md file is *half useful* in my opinion. While the pull requests messages are important, the amount and organization of the commits in a pull request are even more important. Knowing this, the content of the PULL_REQUEST_TEMPLATE.md file will appear **after** all the commits where committed (pun intended) and **after** the contributor or author did the possible mess. This leads to reviews harder than they need to be and may even force contributors and authors to learn advanced GitHub methods.

On the other hand, the [ISSUE_TEMPLATE.md](https://help.github.com/articles/creating-an-issue-template-for-your-repository/) file **it is absolutely needed and useful**. Because we can have super detailed guidelines on how to report errors, but the *bug reporters* are mostly end users. And the end users that [RTFM](https://en.wiktionary.org/wiki/RTFM) are an endangered species and counted with the fingers of one hand (LOL).

Speaking about guidelines. The current CONTRIBUTING.md file on this repository reads:

> The title must be in the format `spice name: simple description of the problem`.

It shouldn't be the *only* xlet name the one specified, but the xlet UUID also. Why? Because there are several applets with similar name or even the exact same name. So, in my opinion, it should read:

> The title must be in the format **Spice name (Spice UUID): simple description of the problem**.

In my opinion, the ISSUE_TEMPLATE.md file should be created right now and with the following content:

```markdown
    The title of this issue must be in the format **Spice name (Spice UUID): simple description of the  problem**.

    ### Issue description
    Describe your issue in detail.

    ### Steps to reproduce
    1. Step one.
    2. Step two.

    ### System information

    ```
    Paste here the output of the following command run on a terminal: inxi -xxxSc0 -! 31
    ```
```

With a *fed spooned* template like this, all of you can close issues on sight with absolute zero remorse.

**Comment by collinss** [comment]
One problem with requiring the uuid is that the end user is (almost) never going to know the uuid or the author's name. It's not really something they should as a general rule. If we are going to require the uuid in the title and/or the author referenced in the description, we will need to provide instructions on how to find that information. Those instructions need to consist of more than just ```right-click -> about``` because at least some of the issues are going to be the applet not loading in the first place, which in turn means they can't open the about dialog.

On top of that, many of the people who report issues probably will not be repeat reporters (and may not even be familiar with github and bug reporting), so they will not be aware of the proper procedures, or how to obtain the necessary information.

Pull requests, on the other hand, will almost always be by someone who contributes regularly, so we can reasonably expect a lot more from them than the average end user.

Finally, I think it will be extremely valuable to use tags to organize the issues so that a developer can quickly check what issues are open against a particular spice. I know it will be a little extra effort at first, but I'm willing to put that effort in, and once it gets moving I think it will be much easier to maintain.

**Comment by jaszhix** [comment]
> It's not really something they should as a general rule.

Its on the same page of the spice's page on the website. If they find their way on Github, the least they can do is know what they're reporting about.

Honestly, I am not liking the execution of this whole applet repo experiment. You guys at least need Github services tied into the website. It seems like you guys overhauled the CSS of the spices site, but didn't do anything about its technical issues. 

Why not have the same functionality of the old site, but using this repo as a back-end? Then extend the UI features based off of a service interfacing with Github. I'm sure its not impossible to isolate a list of libraries that can cause damage like Gio, GLib, etc, and use regex to flag applets for malware checks. I think this whole process could have been more developer friendly, but wasn't because it was easier for Linux Mint.

**Comment by collinss** [comment]
> It seems like you guys overhauled the CSS of the spices site, but didn't do anything about its technical issues.

Which technical issues are those, exactly?

> Why not have the same functionality of the old site, but using this repo as a back-end?

Sorry, I'm not really understanding how that will be any different from what is already happening. What functionality are you referring to?

> I'm sure its not impossible to isolate a list of libraries that can cause damage like Gio, GLib, etc, and use regex to flag applets for malware checks.

The problem is that many of those libraries are used extensively and are indispensable to many applets. As for auto-flagging malware, that is not really realistic. There are so many ways that someone could insert malicious code into an applet that could circumvent whatever checks were put in place. Consider anti-virus software - no matter how good it is, it still needs the virus definitions updated regularly because it is impossible to identify all malware through algorithms alone.

I know the current setup is not ideal from an applet developer's standpoint (many of the applets and desklets here are mine so I get it), but I don't really see a better solution.

**Comment by jaszhix** [comment]
I think Lester made a good point in Cinnamon's [issues](https://github.com/linuxmint/Cinnamon/issues/6130). This repo does rob developers of a degree of technical ownership. When I'm waiting for a prolonged period just to get a bug fix and some generic tooling boilerplate through, it seems a little absurd.

This is an overreaction to [security issue scares](https://www.reddit.com/user/flakka_mint) occurring earlier last month, and taking it out on developers is lame. LM didn't offer developers a way to upload new versions for two weeks. Then to go through this process feels like a chore, and an annoyance.

**Comment by jaszhix** [comment]
> Sorry, I'm not really understanding how that will be any different from what is already happening. What functionality are you referring to?

What you did was add manual intervention on submission. That is not an "application". That is unnecessary bureaucracy. 

> As for auto-flagging malware, that is not really realistic.

Google uses selenium tests for this kind of thing in Chrome. I think what would have been more appropriate is having two tiers of applets - "trusted" and "untrusted". Like, because I'm new I would be "untrusted" for a while, but then after a period of time my updates could be pushed through automatically.

**Comment by collinss** [comment]
> This repo does rob developers of a degree of technical ownership.

If developers want to develop their applets outside of the Linux Mint organization, there is nothing stopping them. Having their work hosted on the spices website and available for download in Cinnamon settings has been a service that Linux Mint has offered for both the users and the developers. Unfortunately, over time the lax policies governing the use of that service have led to multiple complications, not and not just security issues, and so the policies had to be changed. If you wish to use those services, you should be prepared to live with the policies surrounding them. If you can't, or don't want to, you are always free to stop using the service, and have your code removed from this repo. Some have already (including Lester).

Part of the problem is that these applets are being offered through Linux Mint products and websites. From and end-user perspective, it's still coming from Linux Mint, and there are consequences to that. One is that the user will tend to trust what is downloaded because it comes (in their mind at least) from Linux Mint. Another is that when half the applets don't work, and some aren't even installable, that reflects badly on the organization.

> I think what would have been more appropriate is having two tiers of applets - "trusted" and "untrusted". Like, because I'm new I would be "untrusted" for a while, but then after a period of time my updates could be pushed through automatically.

That is actually how it works now, except that it's the developers who are 'new' or 'trusted'. There are some applet developers who have been around for quite a while, and are trusted enough that their code doesn't really need a review before being merged. Some of them have even been given push access to this repository, and I expect that that number will grow as time goes on.

**Comment by jaszhix** [comment]
> Having their work hosted on the spices website

Github.

> From and end-user perspective, it's still coming from Linux Mint

I think this is what I disagree with most though. You guys assume users are not seeing that the software they are using is not coming from Mint. Published technically? I think anyone above an elementary level of cognitive abilities can see that Cinnamon spices is hosting third party content. Every applet ends with "by ____". If you guys want to clamp down on the distribution channel for Cinnamon, fine, but if LM is unwilling to compromise on features and developer input then I'm done donating to and using Linux Mint. 

I'm never taking my applets down though because you'll just fork them back up like you did with Lester's. Which is fine, but you're still hosting his code. So you only took his name down.

**Comment by jaszhix** [comment]
> Another is that when half the applets don't work, and some aren't even installable, that reflects badly on the organization.

This is 100% Linux Mint's fault. Your website never had filters by version, so the user experience suffered.

> There are some applet developers who have been around for quite a while, and are trusted enough that their code doesn't really need a review before being merged

Look at the 71 issues I've closed on my ITM repo, because people need a groupable window list. There should be more metrics to "trust" than time. That's not really fair.

**Comment by NikoKrause** [comment]
I'm don't want go any further into this discussion. Just a couple of notes. I won't reply to any comments to my comment.

> offered to help with the website development (would have for free), but was ignored.

clefebvre is in charge. He has a lot of projects going on simultaneously (KDE, Xfce, MATE, Cinnamon, Spices, etc.) and a lot of channels to contact him (EMail, IRC, GitHub, LinuxMint blog, Segfault, Slack, etc.)
It's hard to catch, follow and remember every single comment. I don't think your offer was ignored on purpose.

> And failure to provide an API that doesn't account for compatibility.

In my experience Cinnamon is a DE, which doesn't break stuff with easy heart. They still use the old Mint-X theme by default! Some applets still work after 2-4 years. Some of the broken apps I saw were just broken, because they imported stuff they never used (e.g. binary clock desklet imported Calendar stuff and never used it). But at some point it's inevitable to break stuff (e.g. removing box pointers) without bloating your stuff. GNOME for instance seems to break their API with every release. Don't judge on that. I don't have much experience with other DE, so I don't have much to compare ;)
Failures were made. That is obvious. And that's why it has been changed now. The whole process is very new to everyone. And there are sure things, which could be improved. And there are still things to come (OAuth) and will be improved. But it will grow and develop with time. New mistakes will be made as well. That's unavoidable. With every big change you have people, who say they liked the old system better or would have done this or that differently (e.g. as Ubuntu moved to Unity, Microsoft moves form Windows version to Windows version). That's naturally. 

> You guys assume users are not seeing that the software they are using is not coming from Mint. Published technically? I think anyone above an elementary level of cognitive abilities can see that Cinnamon spices is hosting third party content. Every applet ends with "by ____".

A few years ago, when I started with Cinnamon (I was very new to Linux), I saw available applets online. And I thought they were from LinuxMint. Because the website said as well linuxmint.com. Only later I realized, that all this people offering those applets are not from LinuxMint, but pretty much everyone could upload there. As I said I was very knew to Linux per se. And I didn't knew, who belongs to LinuxMint and who not. And it's kind of frustrating, that stuff didn't installed or crashed. Also not everybody does understand English. They have to play Point&Click with the applets, if they want to know what those are doing.

> if LM is unwilling to compromise on features and developer input then I'm done donating to and using Linux Mint

LM is open to feature requests and improvements in my experience. But you can't expect every feature request to be implemented and done (immediately). (http://www.bartleby.com/17/1/62.html) They decided to do it this way on GitHub. It's knew and has some flaws. They have reasons to do this simple for several reasons. Having enough people to do spices as well is one of them. Spices is now a thing that needs more time to spend with than before. Time the developers would usually spend for one of the other projects or Cinnamon itself. Also you have to keep in mind. Even if you have enough people now, you don't know how long they stay. If some of them step back, you need other people do step in. (Looking at the long run.) I'm not saying that this is ideal as it is. I wasn't happy either as I heard at first, that I have to fork the whole repo with all it's applets to upload my applet. And there have been many complains since. But in the meantime I closed peace with this fact right now. (As a sitenote: Users asked for years to implement vertical panels. Now this is possible. Users also ask for years to have a Desktop grid in Cinnamon. It's something on the list for a while, but it needs time. Step by step.)

> I'm never taking my applets down though because you'll just fork them back up like you did with Lester's. Which is fine, but you're still hosting his code. So you only took his name down.

As far as I know Lester removed all his applets on spices. And I haven't seen anybody uploading them since. Let me know if I'm wrong with this.

> There should be more metrics to "trust" than time. That's not really fair.

Trust is a very complicated thing and very hard to define (speaking of setting "metrics" to trust). You can't set up a checklist and expect someone to trust you, if he checked everything on this list. (<- a lot of stuff can discussed about this topic and it can get very philosophical. Another reason, why I don't want to reply to answer comments to the lines I write right now)

Now to getting specific. Your last Pull Request was over 5000 lines (you squashed 3 applets in there). Even with a quick glance over it, you need some time for that.
That's what I meant with "it's pretty knew to everyone". 
We need to work out some rules. One of them will be, that it should be only 1 applet per Pull Request. That way most stuff will be merged faster. As clem said the beginning is rough and slow, but it will get faster with time.

I hoped I didn't offended or attacked anybody with the lines above. If somebody feels offended, it wasn't my intention. I'm sure every one of us (including me) is curious how this project will grow in the long run.

**Comment by jaszhix** [comment]
No offense taken. I don't mind my code being reviewed - I think the main thing that triggered my rant was the stance of blaming developers, and defending the lack of efficiency. At this point I don't care though. I have to keep my job, and when I code for fun I do it for me - I don't have time to track two repos for one project. If there's an ITM issue opened here with missing information, I'm just going to ignore it.

**Comment by jaszhix** [comment]
>  And I haven't seen anybody uploading them since. Let me know if I'm wrong with this.

> I won't reply to any comments to my comment.

Ok.

**Comment by collinss** [comment]
I never said, nor have I ever heard anyone else from the Linux Mint team say anything that would place blame on the applet developers for the situation that we're in. I'm sorry if my comments were taken that way. All my comments above were to try to explain why the decisions were made, and why it is the best course to take. The team certainly took the applet devs into consideration, and we tried to accommodate them as much as possible in developing the policies and procedures going forward, but at the end of the day, the needs and concerns of the end user take precedence.

> If there's an ITM issue opened here with missing information, I'm just going to ignore it.

I don't blame you. One of the issues we've been focusing on heavily is how best to handle bug reports and feature requests so that we can get the right information to you, the developers, without all the extra stuff that you don't need to worry about.

**Comment by jaszhix** [comment]
That's good to hear then. Thanks for the clarification.

> at the end of the day, the needs and concerns of the end user take precedence.

I agree. It does seem odd though to develop policies over a malware concern that has no precedent for Cinnamon and to do it this aggressively. I remember the very next day after the security scare I mentioned above, applet upload functionality was disabled. It just seems like you guys wanted to prove the FUD spreaders wrong and went too far in the direction of control. That's fine for now, but I don't see it as being tenable long term - so I hope the team considers some of the suggestions as far as the website goes.

**Comment by mockturtl** [comment]
> Finally, I think it will be extremely valuable to use tags to organize the issues so that a developer can quickly check what issues are open against a particular spice. I know it will be a little extra effort at first, but I'm willing to put that effort in, and once it gets moving I think it will be much easier to maintain.

:heart:  Please do.  

(I wrote a [client for the Labels API](https://github.com/mockturtl/squint) to help reduce this busywork.  Feature requests welcome!)

**Comment by collinss** [comment]
@jaszhix There were actually several reasons the applets were moved to Github. Security was certainly a big one. When the spices website was first created, security was not a big issue. Cinnamon was fairly unknown, and the potential payoffs of an attack based on Cinnamon technology weren't worth the effort. However, Cinnamon and Linux Mint are now very popular, and quite well known, and that makes them a target. The hacking that you refer to is evidence of that, but I believe there were other reasons Clem was worried about security as well. It also wasn't as knee-jerk a reaction as it seemed from the outside. There have been discussions about doing this for a while, but they couldn't be made public until action was taken because it would basically be an open invitation for someone to exploit the weakness in our applet system.

Another big reason for the move is that over time, the spices website has become bloated with old abandoned applets and themes that no longer work. This makes it much harder for people to find the good working ones, and reflects poorly on the applet developers, the spices website, and even Cinnamon itself. We could, of course, have taken the time to clean it all up, but if we just left the same system in place, it would have ended up in the same state all over again, but this time, it probably would happen even quicker.

On top of that, any time one of us wants to make a cool addition to Cinnamon, we've always had to weigh the risk of breaking api for existing applets against the value of the change we want to make. Sometimes we decide that it's not worth it, and the users miss out on the feature. Other times (vertical panels and removing the boxpointers were two recent examples) we decide the need or benefit outweighs the potential downsides of changing the api. In still other situations, we find a way to implement the feature, while still maintaining compatibility with older code by adding additional hacks and programmatic glue, but at the cost of code that is harder to read and maintain or that introduces unnecessary complexity (for example, switching over to the new xlet settings).

By moving everything to a central github repository, we solved all of that (or at least made it much easier to solve). We are no longer beholden to the api, because we can more easily be in communication with applet devs about upcoming changes in the api so you can adapt to it before the new version is even released, and even make the necessary changes ourselves if need be (such as for abandoned applets).

**Comment by jaszhix** [comment]
@collinss Thanks for elaborating on this. It probably seems like I'm complaining a lot, but they're mostly nitpicks and I really do appreciate the work that goes into making Cinnamon what it is. I know I'm not alone in that sentiment. I'm willing to work with the community here, and give you guys time to calibrate.

**Comment by NikoKrause** [comment]
Issue template added. Also updated CONTRIBUTING template.
We'll see how it will work out and improve it, if necessary.
I'm closing this for now. Suggestions for template still welcome.
