### ISSUE TITLE
[radio@driglu4it] Applet icon is light on light background

### ISSUE THREAD

**Issue by fredcw** [linuxmint/cinnamon-spices-applets#3512]
* Cinnamon version 4.8
 * Distribution - manjaro
 
@jonath92 

Applet icon is white on light theme background

![Screenshot from 2021-02-04 11-30-32](https://user-images.githubusercontent.com/58893963/106891499-ac0b5d00-66e2-11eb-8bc9-ebd05b0e1689.png)

Other ideas/suggestions:

1. When the applet is removed from the panel, the radio station continues playing!

2. Perhaps "copy current song title" should be on left click menu instead of right click. Not sure about this though.

3. The applet tooltip could show 2 things: the currently playing song title and the current volume e.g  "Some band - Some song (Volume 62%)"
If the volume was in the tooltip, it would eliminate the need for the notification that the volume is at max.

Edit: Actually, another option is put the volume on the next line by inserting a newline "Some band - Some song \n Volume 62%"?

**Comment by jonath92** [comment]
Thanks for the feedback @fredcw. I fill fix point 1 later. 

I am not sure about point 2 as I think it is actually nice to have the radio station list and the copy feature somehow separated as these are two different use cases. Having it in the same list with the radio stations would make it a little more time-consuming to get with the cursor to the right station or to the copy feature. This is even more the case when more options get implemented (I already have implemented a 'download from youtube' feature locally).  Although I must admit that the amount of time to get the cursor to the right position is not significant and according to this logic also the Stop and Pause (in future) icon would go to the right click menu).  For now however I probably will leave it as it is as having it on the left click menu is not clearly better as on the righ click menu.   

> The applet tooltip could show 2 things: the currently playing song title and the current volume

I basically agree with point 3 and I had this already in mind for some time. It is IMO very bad that the volume isn't shown at all in the moment.  But just for clarity - what is about the station which is currently shown? Personally I like to know which station is running which was the reason why I implemented  "Show current radio station on the panel" in the settings. But I can imagine that not everybody wants this as it also takes a lot of space in the panel. That's why I didn't remove it from the Tooltip. Also I can understand that you want to see the title in the tooltip but IMO this is again a personal preference as I actually prefer to show the title in the panel by activating the "Show song information on the panel"  option of the sound applet. That's why I have thought about making the tooltip content user-defined in the settings.

**Comment by fredcw** [comment]
I found the white icon problem

line 89 should read: `const color = (this.mpvPlayer.getPlayPauseStatus() === "Playing") ? this.color_on : ""`

**Comment by fredcw** [comment]
>"Show song information on the panel" option of the sound applet.

Nice, I didn't even know about this.

**Comment by fredcw** [comment]
@jonath92 The menu width changing because of the timestamps at the bottom, maybe you could fix that by using a monospaced font just for the timestamps? Something like .set_style("font-family: mono;") on the label?

**Comment by jonath92** [comment]
You mean the position an the stream length? 
![image](https://user-images.githubusercontent.com/49979415/130269040-f9a39e42-a8b0-4087-b577-a8ef21a4a4a6.png)

I can do this of course but 
I don't see that the width is changing?

**Comment by fredcw** [comment]
>You mean the position and the stream length?

Yes, the width of the menu changes. I use a custom theme but it happens with Mint-Y-Dark as well.

https://drive.google.com/file/d/1zWiVS9PV0AQM6BxETE1rh-tygW-ImqKt/view?usp=sharing

(probably best to download the video as it seems to freeze if you try to play it in the browser)

**Comment by jonath92** [comment]
It took me some time but I was able to reproduce it. I think you have changed your default font? It only occurs on my pc with a non default font. Anyway it is fixed now.

**Comment by fredcw** [comment]
Yep, laila. I didn't realise that so many non-mono fonts have mono digits.
