### ISSUE TITLE
weather@mockturtl

### ISSUE THREAD

**Issue by French77** [linuxmint/cinnamon-spices-applets#3553]
```
 * Applet version/Build date: Versie 3.0.2 (2021-02-11 08:27:28)
 * Cinnamon version:4.8.6
 * Distribution - ulyssa 20.1
 
 


 ```

**Notify author of applet**
@Gr3q 
@Pjotr123 “last editor nl.po“

**Issue**
Not possible anymore to merge updates into own repositorie due to conflicts in the dutch translation

**Other information**
### »Screenshot merge pull request
![Merge pull request](https://user-images.githubusercontent.com/3099270/107846089-376ea780-6de1-11eb-8d64-21b6f88091bf.png)
#### Could these warnings in the translation be the cause of it
![Vertaling](https://user-images.githubusercontent.com/3099270/107846182-fc20a880-6de1-11eb-9ecf-b07ac41b8e4b.png)

**Comment by Pjotr123** [comment]
No, it can't be because of Celsius and Fahrenheit beginning with a capital, because that has been so for a long time (except for a short period). That's only a harmless warning in Poedit, because Poedit apparently doesn't know that in Dutch, Celsius and Fahrenheit need to begin with capitals.
I've removed Weather, pulled the latest build and re-installed it, and there are no conflicts in my system....

**Comment by Gr3q** [comment]
I could merge without issues as well.

This warning only happens because on your branch nl.po was edited while this PR https://github.com/linuxmint/cinnamon-spices-applets/pull/3550 was approved and merged to upstream's master.

You should try merging the upstream master into your branch (or rebase your master then merge that) to resolve the conflict.

btw I'm also make sure temperature units begins with capitals, as they should

**Comment by French77** [comment]
Okay both thanks for your response,going to see if I can solve it by removing the repository and reinstalling it

**Comment by French77** [comment]
done will close this issue now
