### ISSUE TITLE
weather@mockturtl : App says rain but website says snow.

### ISSUE THREAD

**Issue by ByteEnable** [linuxmint/cinnamon-spices-applets#3576]
```
 * Version 3.0.1 (2021-02-03 00:01:21)
 * 4.8.6-1.fc33
 * Fedora 33
 * NVidia GTX1060 - 460.39
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors
 ```

**Notify author of applet**
weather@mockturtl 

**Issue**
Weather app says its raining but the weather website says its snowing.

**Steps to reproduce**
Unknown

**Expected behaviour**
For app to match weather website.

**Other information**
![Screenshot from 2021-02-14 22-06-38](https://user-images.githubusercontent.com/5896865/107904317-656bfd00-6f43-11eb-93d3-7dba5b402aeb.jpg)
![weather-fail](https://user-images.githubusercontent.com/5896865/107904330-6b61de00-6f43-11eb-97f0-8c43107585de.jpg)

**Comment by Gr3q** [comment]
If you would use US Weather I would say it's plausible because I wrote the logic to get the information from stations, but with OpenWeatherMap there isn't much to go wrong.

There are 2 options why this can happen:
* Your applet refresh rate is high (more likely, e.g. it changed between the last refresh and the time your checked the website)
* You didn't allow location access on the website and searched for the city, the coordinate difference can cause the difference in the observation.

Can't do much about this issue because I display the information coming from OpenWeatherMap as-is.
