### ISSUE TITLE
Longitude and latitude fields are integer only

### ISSUE THREAD

**Issue by julesbl** [linuxmint/cinnamon-spices-applets#3637]
```
 * Applet version/Build date (to be found in "About.." or in "metadata.json")
 * Cinnamon version (cinnamon --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of applet**
@

**Issue**
The longitude and latitude fields in the save locations form are integer only
Fixed point numbers are truncated to integers

**Steps to reproduce**
Click on add a new entry
Fill in the fields
On saving long and lat are trucated to integer

**Expected behaviour**

**Other information**

**Comment by NikoKrause** [comment]
Hey, which applet are you refering to?

**Comment by julesbl** [comment]
Sorry about that, thought it said, Weather (weather@mockturtl)

https://cinnamon-spices.linuxmint.com/applets/view/17

Not sure setting the long, lat by hand is doing anything either, still showing a different one in the header, but that might be the weather station they are defaulting to, for the UK Met office

**Comment by NikoKrause** [comment]
@Gr3q

**Comment by Gr3q** [comment]
Hi, yeah I'm aware of this (and it sucks).

First, the workaround I was using is to type in the lat and long but **not** type enter at the end. That way it won't round the coordinate for you. The list view can only display the coordinates up to 5 decimal places, but internally the entire number is stored which was entered.

~~Now, for the fix. I've changed the step the '+' and '-' buttons changing the coordinates, they increment/decrement in 4 decimal places. Also displays 4 decimal places. Looks like this now: 
![image](https://user-images.githubusercontent.com/22377521/109349964-a5e64780-786e-11eb-95d6-563d83530dca.png)~~

~~This gives us around 11m accuracy (the workaround still works).~~

~~This is still an issue, because I would like to show at least 6 decimals in both places (0.11m accuracy), but that seems to be impossible (the entry seem to revert to whole numbers after steps under 0.0001)~~

Edit: It seems if I enter a step to increment/decrement with like this: `0.000105` I can force the entry to display 6 decimals. This makes the buttons more useless than they were before (and they were completely useless before...), but at least it's displayed properly.

Let me know if it's not a suitable solution.

Looks like this now with the fix:
![image](https://user-images.githubusercontent.com/22377521/109351011-6882b980-7870-11eb-9d18-ed8777104f54.png)
