### ISSUE TITLE
Opening Cinnamenu with Super key conflicts with Super+R to open Run dialog

### ISSUE THREAD

**Issue by urbster1** [linuxmint/cinnamon-spices-applets#3675]
```
 * Applet version/Build date 4.11.2
 * Cinnamon version 4.8.6
 * Distribution - Mint 20.1
 * nVIDIA GeForce GTX 650 Ti with nVIDIA drivers
 ```

**Notify author of applet**
@fredcw

**Issue**
When mapping left Super key (or Hyper-L as it is called in Cinnamenu) as single key to "Keyboard shortcut to open and close the menu", I am unable to use left Super key as modifier for other shortcuts e.g. Super+R to open Run dialog.

**Steps to reproduce**
Open Settings for Keyboard --> Shortcuts --> General --> Run dialog and add keybinding Super+R. In Cinnamenu Configure --> Behavior --> Keyboard shortcut to open and close the menu, map Hyper L (leave second key unassigned). Press left Super+R.

**Expected behaviour**
Run dialog should open (Cinnamenu should wait for Hyper L keyup before opening menu).

**Other information**

**Comment by fredcw** [comment]
@urbster1 I can't reproduced this, it seems to be working for me - menu doesn't open until super key is released and super + r works for run dialogue. Is cinnamenu's behaviour different to that of the default cinnamon menu applet? Also, the current version of cinnamenu is 4.12.8 but that shouldn't make a difference because I don't think I've changed the relevant code.

**Comment by urbster1** [comment]
Thanks for your help! I realized I had the Super key mapped to Hyper instead. Reverting this fixed the issue.
