### ISSUE TITLE
World Clock Calendar (calendar@simonwiles.net) - seconds (%S) don't tick (change)

### ISSUE THREAD

**Issue by janos-r** [linuxmint/cinnamon-spices-applets#3706]
uuid: World Clock Calendar (calendar@simonwiles.net)

```
 * Applet version/Build date (to be found in "About.." or in "metadata.json")
Updated on 2021-03-13 09:33:20
 
 * Cinnamon version (cinnamon --version)
4.8.6 

 * Distribution
Mint 20.1, reproduced also on 19.3 

 * Graphics hardware *and* driver used
UHD Graphics 630
 ```

**Notify author of applet**
https://github.com/simonwiles

**Issue**
Very recently, the seconds (%S) stopped ticking. They get stuck on 00 and only minutes keep changing. Please investigate. Seen both on 19.3 and 20.1. Please investigate and fix, I use this every day.

**Steps to reproduce**
1. right-click - configure
2. Use a custom date format
3. add :%S for seconds
4. Watch the seconds being frozen and updating and staying only on 00, the same happens for the seconds in the timezones under right-click - edit world clocks

**Expected behaviour**
Seconds updating every second.

**Comment by janos-r** [comment]
Could pleeease somebody have a look at this? I have stopped seconds for the last 2+ weeks XD How is this flying under the radar?

**Comment by NikoKrause** [comment]
@simonwiles

**Comment by janos-r** [comment]
I just tried the "Timezone Clock" app, and it behaves the same regarding the %S seconds. Could be the same cause.
The default "Calendar" app ticks ok though.
I also tired to write a direct email to Simon Wiles last week (no response yet). I hope this can be resolved at some point. If it works for the standard Calendar app, it should be solvable I guess.

**Comment by janos-r** [comment]
Ok, I found a solution!
But it still feels like a bug.
The seconds on any clock in this app update only, if you enable "Display seconds" in the system native "Date & Time" app.
After that, if you don't want to see them in the main clock, but only in the foreign clock, you have to set a "Use a custom date format" in this app.

I couldn't find the place in the code that does the graphical update. I can only suspect, that the native "Date & Time" app takes control over the panel and doesn't send a time update information? The system time itself is obviously fine (running "date"). I'm really not sure about my assumptions :/ Would love if someone could explain.

If the seconds update is really dependent on the systems "Date & Time", then there should be a message included in this app like "For seconds support, enable it in 'Date & Time' app." or something like that.

**Comment by mscheper** [comment]
> I couldn't find the place in the code that does the graphical update. I can only suspect, that the native "Date & Time" app takes control over the panel and doesn't send a time update information?

I [found the code](https://github.com/linuxmint/cinnamon/blob/6b986f02974dd3a12eb040f7fcbe1389d02d9f66/files/usr/share/cinnamon/cinnamon-settings/modules/cs_calendar.py#L56) for the settings app, and it modifies a system setting called `clock-show-seconds`. I don't know about the scope of these settings, but you're right that the standard calendar applet [uses it](https://github.com/linuxmint/cinnamon/blob/6b986f02974dd3a12eb040f7fcbe1389d02d9f66/files/usr/share/cinnamon/applets/calendar%40cinnamon.org/applet.js#L207), and this applet [does](https://github.com/linuxmint/cinnamon-spices-applets/blob/f51f83baf21f64311732adade3014ff2f0740ac7/calendar%40simonwiles.net/files/calendar%40simonwiles.net/applet.js#L208), too.

> If the seconds update is really dependent on the systems "Date & Time", then there should be a message included in this app like "For seconds support, enable it in 'Date & Time' app." or something like that.

Makes sense to me. But the original author, @simonwiles, hasn't committed any applet code [since 2016](https://github.com/simonwiles/cinnamon_applets/graphs/code-frequency), so it might be up to one of us to do it. I've been meaning to get my hands dirty with Cinnamon applet code, but if somebody beats me to the punch, I wouldn't be in the least bit offended.

**Comment by janos-r** [comment]
I stopped using this app, because as you said, it is unsupported and thus lacks the events feature for example.
Right now, the best way to have the modern calendar look with world clocks, is to use the "Calendar with public holidays" - it integrated both the events from the main app + the world clock feature.
The ultimate solution would be to make a pull request to the main calendar app and convince them to integrate the world clocks feature.
