### ISSUE TITLE
kdecapplet@joejoetv: support new line in KDEConnect Applet

### ISSUE THREAD

**Issue by neesti** [linuxmint/cinnamon-spices-applets#3743]
Hello.
I use KDEConnect Applet version "Version 1.1.1 (2021-04-04 22:37:04)". 
This applet dose not support new line in "Message" field when I want to insert new line into My SMS!
Please support this feature. 
Thank you. 

![image](https://user-images.githubusercontent.com/14938202/114577990-bec98180-9c91-11eb-8e2c-f0e0a43684fe.png)

**Comment by NikoKrause** [comment]
@JoeJoeTV

**Comment by JoeJoeTV** [comment]
Hello @neesti

thank you for reporting this issue, but unfortunately I can't easily add this functionality, because the "Share URL" and "Send SMS" dialogs are made using zenity, which is a scripting tool to make simple GUIs using command line parameters and AFAIK it only supports single line entries.
There is a KDE Connect SMS App that you can start from your application menu or by using the "Launch SMS App" option in the applet. It has a better ui and more functionality than the simple "Send SMS" option but can be wonky sometimes from my experience. Anyways, you can try that and decide if that solves the problem.

I will maybe look into different alternative methods to make a better "Send SMS" GUI later.

**Comment by JoeJoeTV** [comment]
Hello again, @neesti, have now finally rewritten the Applet from the ground up and added custom gtk dialogs for things like the "Send SMS" GUI. It is not yet merged, but you can view the progress here: https://github.com/linuxmint/cinnamon-spices-applets/pull/4656

**Comment by JoeJoeTV** [comment]
@neesti The change has been merged and the new dialog supports newlines.

**Comment by neesti** [comment]
> @neesti The change has been merged and the new dialog supports newlines.

It's OK. 
Thank you so much.
