### ISSUE TITLE
radio@driglu4it: background when opening applet is too transparent

### ISSUE THREAD

**Issue by vlatkoB** [linuxmint/cinnamon-spices-applets#3831]
Cinnamon version 5.0.3
Distribution - Arch

@jonath92

When clicking on the applet, the panel that is opened is very transparent, and if a white background is behind it, not possible to see anything, nor stations list, nor the playback buttons.

Maybe setting background of the panel to black, or introduce a setting to select the colour and transparency?

**Comment by jonath92** [comment]
@vlatkoB Thanks for reporting this issue. 

> When clicking on the applet, the panel that is opened is very transparent, and if a white background is behind it, not possible to see anything, nor stations list, nor the playback buttons.

Sorry for the inconveniences.  I guess you mean the popup menu (using the term "panel" is a little bit confusing as the bar on which the radio icon and the other applets are placed, is usually called "panel")? The popup isn't transparent on Cinnamon 4 on pretty much every theme I have tested but I haven't tested the applet yet on Cinnamon 5 but I will test on the weekend. 

> Maybe setting background of the panel to black, or introduce a setting to select the colour and transparency?

The background should be specified by the theme but never by transparent. Can you therefore tell me which theme you are using?

**Comment by jonath92** [comment]
Ok I tested now also on Mint 20.2 which has `cinnamon 5.0.2` installed and it works without problems. So I really need more information. Especially about the theme. Also is this only happen with the radio applet or also with other applets?

**Comment by vlatkoB** [comment]
Not with other applets, only this one. Desktop and Windows borders "05-Crunchy-green", Icons, Controls and Mouse "Adwaita".

![Radio-bkgrnd](https://user-images.githubusercontent.com/2315313/124306540-d31d6c00-db66-11eb-966c-03b1356cd0a4.jpg)

**Comment by jonath92** [comment]
Where is the theme from? I only find [this](https://cinnamon-spices.linuxmint.com/themes/view/Ambiance-Crunchy) "Crunchy" theme which looks ok on my pc. Did you customize the theme? For debugging it would be best if you could just attach the folder of the theme as compressed file here or by sending in a mail to JonathanHeard92@gmail.com

**Comment by vlatkoB** [comment]
Yes, it is that Crunchy. I do not remember I was doing anything to it.

[05-Crunchy-green.zip](https://github.com/linuxmint/cinnamon-spices-applets/files/6756187/05-Crunchy-green.zip)

**Comment by jonath92** [comment]
Ok, with this theme, I can reproduce the issue. I have compared the `cinnamon.css` file of your theme with the Crunchy theme from the cinnamon store and your file is missing a style for the class `.menu`.  So you can fix it by adding the following to the `cinnamon.css` file: 

```
.menu {
	background-gradient-direction: horizontal;
	background-gradient-start: #292825;    /*Dark color2*/
	background-gradient-end: #4D4B46;    /*Dark color1*/
	border: 1px solid rgba(77, 75, 70, 0.8);    /*Dark color1*/
	border-radius: 5px;
	color: #fff;    /*White */
	font-size: 9.5pt;
	min-width: 100px;
}
```
As this bug only occurs on the radio applet and not on other applets, I actually should fix it or at least investigate further but as the bug only occurs on very few themes, a workaround is available and I don't expect this to be an easy fix, it doesn't have a high priority for me. But let me know when this workaround doesn't work for you or has some other disadvantages. 

Out of curiosity, is there a reason why you are using the "Full Color" Icon Type and not the "symbolic" Icon Type (you can change the icon type in the settings)? I am interested in that because I have never seen a user actually not using the "symbolic" icon and I was thinking about removing the option but when you prefer the 'Full Color' Icon I will obviously leave the option.

**Comment by vlatkoB** [comment]
I did the suggested changes to `.css` file, and the problem is now solved, so this issue can be closed. Thanks for putting so much time and effort into this. Much appreciated, indeed.

Although, it changed all other applet pop-ups appearance (much darker), but I can live with that.

As for the icon, when I select `symbolic`, it appears very small, like small letter "c" (I'm on 4k, maybe it is fine for others). 
`Bicolor` is really big and has too much white colour, and stands out too much among other icons, so only `Full Colour` blends in fine with my theme.
Please leave it. :-)

**Comment by jonath92** [comment]
I am glad it is working now for you. I think the issue can only be closed by someone from the Linux Mint team or by the person who has opened the issue. So it is probably easiest when you close the issue. 

When you like the applet, feel free to like it (if you not already did so) on the [cinnamon site](https://cinnamon-spices.linuxmint.com/applets/view/297) as this makes the applet more popular and it helps me to improve my reputation as a developer. 

> Please leave it. :-)

Yes I will leave it for now. But one last question: Do I understand you correctly that you only prefer the Full Color Icon because the symbolic icon doesn't look good on a 4K monitor? Or in other words would you care if the option would be removed once the 4K issue is fixed? I won't fix the issue in the short term but I will try to fix in the long term. I don't like the "Icon type" option for multiple reasons. One reason is that the term "Icon Type" is very confusing from a technical point of view as there are three types in the dropdown list (`Full Color`, `Bicolor`, `Symbolic`) but the library used in the code only differentiate between `Fullcolor` and `Symbolic` Icon Types, i.e. the `Bicolor` Icon type is technically actually a `Fullcolor` Icon. You can imagine that using the same term for two different things is not helpful for development :rofl:. When I keep the option I definitely should rename the term in the settings at some point in the future which however would require some code to update the settings from existing users to enable backward compatibility. However when I just remove the option I could save my time for this and make the code shorter and easier to maintain. Another reason why I think that removing the option is reasonable is that also most default cinnamon applets (such as the sound applet) only have symbolic icons.  But in the end the most important thing is obviously that the users are happy and that's why I am really interested in your opinion.

**Comment by vlatkoB** [comment]
ok, thanks. :-)

**Comment by fredcw** [comment]
@vlatkoB 
>when I select symbolic, it appears very small

Not sure if this is the problem but you can change the symbolic icon sizes in Panel settings>Panel appearance.
