### ISSUE TITLE
[Feature Request] ScreenShot@tech71 - Add "open with"

### ISSUE THREAD

**Issue by bitboy85** [linuxmint/cinnamon-spices-applets#4231]
```
 * Applet version/Build date 2021-12-13 13:57:01
 * Cinnamon version 5.2.7
 * Distribution - Mint 20
 * Graphics hardware *and* driver used
 ```

**Expected behaviour**
Please add an option / drop down selection to open the screenshot with a specific program like picture viewer or gimp

![image](https://user-images.githubusercontent.com/6197580/150422044-1412b3e9-5ff6-48b5-bb13-c96801877527.png)

**Comment by fredcw** [comment]
This is a very simple applet that just calls Gnome Screenshot application so all the features you see are part of Gnome Screenshot rather than the applet. I think you version 3.36.0 of gnome screenshot which is what comes with Mint 20. The latest version of gnome screenshot (version 41) has even less options.

**Comment by bitboy85** [comment]
Thx for clarification. I found the tool will get replaced anyway so i opened a new request here: https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1954
