### ISSUE TITLE
windowlist@cobinja.de - When cinnamon restarts, window order is reset

### ISSUE THREAD

**Issue by StargazerA5** [linuxmint/cinnamon-spices-applets#4291]
```
 * Applet version/Build date 2021-12-13 07:58:56
 * Cinnamon version 5.2.
 * Distribution - Mint 20.3
 

 ```
**Notify author of applet**
@cobinja

**Issue**
When Cinnamon is restarted, window order is scrambled.  I use ungrouped windows so all are displayed in the applet and I often have ~10-20 open in my main workspace.  Other work spaces typically have fewer.  Restarting Cinnamon will cause their order to change requiring me to move the windows back into the order I want.  This gets time consuming.

**Steps to reproduce**
1. Open a large number of windows of various applications (Approx 10-20 , some windows will be from the same application eg multiple browser windows) with the applet configured not to group them.
2. drag and drop windows into a specific order in the applet
3. restart cinnamon
4. windows will be in a different order

**Expected behaviour**
Windows will retain prior order after Cinnamon restart.

**Other information**

**Comment by sangorys** [comment]
+1

Yes, this is very tiring !!!
There is the same issue on wondow-list@cinnamon.org

A workarround should be to have the "pin" option to be sure about the order

**Comment by Cobinja** [comment]
Changing this would imply writing to disk on each change, when a new window appears, when a window disappears etc. For peformance reasons I will not change this.

**Comment by StargazerA5** [comment]
Does it truly have to be written to disk or could it be to a file in RAM?  The ask is for when Cinnamon is restarted, not when system is restarted, so RAM would persist.

**Comment by Cobinja** [comment]
A Cinnamon restart means a new process. That new process does not have access to the old process' memory. Storing to RAM would mean an additional process just to store window positions. Nope.

**Comment by Drugwash2** [comment]
How often does a user restart Cinnamon in a session?
Window order can be stored in memory, updated whenever necessary, and only saved to disk and reloaded upon Cinnamon reload.
Shouldn't be too hard provided Cinnamon signals its reloading in a way that an applet could hook and act upon.
Just sayin'...

**Comment by Cobinja** [comment]
Cinnamon is also restarted if it crashes and if it hits a certain memory limit (yes, that memory limit can be configured), e.g. due to misbehaving applets, desklets or extensions (for which the spices loader in cinnamon-settings is not the only possible source). Especially in the first of those cases it can't signal beforehand.

**Comment by Drugwash2** [comment]
Indeed there are certain uncommon situations when a signal cannot be sent but those can be called exceptions to the rule, and hopefully the developers will do their best to contain such exceptions and limit them in frequency.

On the other hand such exceptions could provide a hint to the user that something wrong has happened, and maybe they will try and investigate, maybe find the root cause. If Cinnamon crashes/restarts are completely transparent the workflow would indeed be (almost) undisturbed but in the long run could lead to worse situations, so maybe getting a hint that something is wrong by the mere fact that window positions changed in the panel would be enough for the user to start checking for errors.

Either way I personally believe the advantage of having the window order preserved between voluntary Cinnamon reloads, which could help for a future **session restore** function, would be worth at least a thought.
