### ISSUE TITLE
weather@mockturl - Unexpected Error in Cinnamon 5.4.10

### ISSUE THREAD

**Issue by jorgenqv** [linuxmint/cinnamon-spices-applets#4429]
```
 * Applet version - 3.2.7
 * Cinnamon version - 5.4.10
 * Distribution - Linux 5.18.17-1-MANJARO 1 SMP PREEMPT_DYNAMIC Thu Aug 11 18:43:37 UTC 2022 x86_64 unknown GNU/Linux
 * Graphics hardware - 00:02.0 VGA compatible controller: InnoTek Systemberatung GmbH VirtualBox Graphics Adapter
```

**Notify author of applet**
@Gr3q

**Issue**
The applet shows Error and expanding it shows Loading... and  Unexpected Error While Refreshing Weather, please see log in Looking Glass

**Steps to reproduce**
Run the applet in latest Cinnamon 5.4.10 in Manjaro Linux

**Expected behaviour**
The applet collects and shows weather info

**Other information**
See Looking Glass Log

[Looking_glass_log_Cinnamon_5-4-10.txt](https://github.com/linuxmint/cinnamon-spices-applets/files/9339574/Looking_glass_log_Cinnamon_5-4-10.txt)

**Comment by jorgenqv** [comment]
Seems to work in Linux Mint 21 with Cinnamon version 5.4.10

**Comment by jorgenqv** [comment]
More info and possible fix on the way?
https://forum.manjaro.org/t/testing-update-2022-08-15-cinnamon-nextcloud-kde-git-haskell-python-glibc-eac-fix/119395/5

**Comment by Gr3q** [comment]
Yeah, it seems it's a bad import, Cinnamon still uses libsoup2.

This probably won't happen too often, I wonder if I should make the applet handle this when we switch to v3 for real.

You can test a fix by changing this file: `~/.local/share/cinnamon/applets/weather@mockturtl/3.8/weather-applet.js`

1. Change imports:
   From this: `const { Message, ProxyResolverDefault, SessionAsync, MessageHeaders, MessageHeadersType } = imports.gi.Soup;`
   To this: `const { Message, ProxyResolverDefault, SessionAsync, MessageHeaders, MessageHeadersType, Session } = imports.gi.Soup;`
2. Change how Session is contructed:
    Change this line: `this._httpSession = new SessionAsync();`
   to this:
   ```javascript
    try {
      this._httpSession = new SessionAsync();
    }
    catch(e) {
      this._httpSession = new Session();
    }
   ```

**Comment by mtwebster** [comment]
Hi, just to give a bit of explanation for this sort of thing:

Soup2 is being removed from repos on other distros because of Soup3. We removed the only use we had of it in core Cinnamon:
https://github.com/linuxmint/cinnamon/commit/dad45bb7799d6deb9eded378492a9220df139944

Unfortunately what that ended up causing as a side effect is importing Soup no longer specifically imported 2 over 3 automatically.

So now, if you have Soup2 and Soup3 installed on your system, the highest version will be preferred by default. We've since added a version preference so extensions don't accidentally import the wrong one:
https://github.com/linuxmint/cinnamon/commit/76224fe409d074f8a44c70e4fd5e1289f92800b9

That won't be until the next point release though. In the meantime you should be able to avoid the issue by adding the version line to the applet directly:
```
imports.gi.versions.Soup = '2.4';
```
Another kicker is that you can't have both loaded across the entire Cinnamon process. So, until *all* extensions get ported to 3, we need to keep using 2. I haven't gotten around to it but I've considered trying to make some sort of shim to allow people to continue using their Soup2 calls but translating them to Soup3. This way we take away any pressure to get them all done immediately.

Anyhow, sorry about this - we should have had that version line in that original commit but it'll be in in the next couple of days.

**Comment by jorgenqv** [comment]
Thank you very much for quick workaround help! However, today a new Manjaro upgrade came along to Cinnamon 5.4.10-2 that fixed the problem in testing branch, also released in Manjaro stable, so now everything works at least on my two installs. 
But thanks again anyway! :)
