### ISSUE TITLE
hwmonitor@sylfurd : Config pages are not visible

### ISSUE THREAD

**Issue by cgvirus** [linuxmint/cinnamon-spices-applets#4439]
```
 * Applet version Version 1.3.1 
 * Cinnamon version 5.4.11
 * Linux Mint 21 Cinnamon
 ```

**Notify author of applet**
hwmonitor@sylfurd

**Issue**

- The Configure pages are not visible.
- Only showing general settings, theme (graph) and theme graph data, The first page

**Steps to reproduce**

- right click on the applet>configure.

**Expected behaviour**

- Should show all configuring pages

**Comment by fredcw** [comment]
Ping @Hultan 

@cgvirus It's not a fix but as a temporary measure, making the configuration dialog wider causes the tabs to appear.

**Comment by cgvirus** [comment]
> Ping @Hultan
> 
> @cgvirus It's not a fix but as a temporary measure, making the configuration dialog wider causes the tabs to appear.

OH! And here I am going through js for finding whats up! XD 
Thanks!

**Comment by Drugwash2** [comment]
Could anyone please try the suggestion I posted **[here](https://forums.linuxmint.com/viewtopic.php?f=120&t=375881)** and confirm whether it works or not with the latest Cinnamon (and with older versions too)?
If it does maybe the Mint developers would implement it natively since as is any further update to Cinnamon would instantly revert the change.
