### ISSUE TITLE
Feature request: keep only favorites apps in the bottom bar

### ISSUE THREAD

**Issue by nicolasmol** [linuxmint/cinnamon-spices-applets#4477]
Since we can have the favorite folders/files on the left, can you please add the possibility  to have only favorites apps here ?
![image](https://user-images.githubusercontent.com/61077647/191771899-5fd4486a-ed30-42d6-8060-3e8f0e379dd6.png)

**Comment by fredcw** [comment]
Hi. Sorry I didn't reply earlier but I only get notified if you mention my github name @fredcw. Tbh, I only like to add an option if I think that many people would find it useful as each additional option makes the options harder to navigate, makes the applet code more complex/prone to errors etc. Unless other people also request this option, I'm reluctant to add it. Thanks for the request though as feedback is always useful.

**Comment by nicolasmol** [comment]
@fredcw 
Because you think this it's consistent ?
![image](https://user-images.githubusercontent.com/61077647/192896349-4f0d8130-ef00-4038-8869-207f16d9918d.png)

**Comment by fredcw** [comment]
Yes, I see the problem now. I'm still reluctant to add another option in the config dialog though. How about if I add it as a hidden option? This would mean manually editing the config file which would be easy enough to do as it's just a .json file.

**Comment by nicolasmol** [comment]
Yes  why not
Or maybe a limit count

**Comment by Drugwash2** [comment]
> I'm still reluctant to add another option in the config dialog though.

You could always rework the configuration dialog by using a custom Python script. That would provide the freedom of grouping options together in a more logical and ergonomical pattern than it is possible in the default JS script.
It may take some time at first but the result might be worth it.
You may take a look at the dialogs in my mods: **[workspace grid](https://github.com/Drugwash2/workspace-grid)**,  **[CPU+RAM monitor](https://github.com/Drugwash2/cpu-ram-mon)**, **[betterlockPlus](https://github.com/Drugwash2/betterlockPlus)**, **[Applet PYE](https://github.com/Drugwash2/Applet-PYE)**.

**Comment by fredcw** [comment]
@Drugwash2 Thanks, I didn't know you could do that.

**Comment by Drugwash2** [comment]
@fredcw There is a very shallow example of that in `settings-example@cinnamon.org` which comes by default with Mint but it's not advertised at all despite its much broader coverage of various controls as well as the time- and sanity-saving ability of not requiring a full applet reload in order to apply any change in the Python script - just close and reopen the Settings dialog. Also, and very important: if Python code goes wrong that script simply will not be loaded; if JS code goes wrong in main `applet.js` or any other loaded JS modules there's a chance even Cinnamon would crash or remain locked forever.
