### ISSUE TITLE
No colors on panel icons in weather@mockturtl

### ISSUE THREAD

**Issue by vpal** [linuxmint/cinnamon-spices-applets#45]
Greetings,

When I uncheck "Symbolic icons" in the configuration the icons on the panel are barely visible very dark and missing colors.
Colors are visible in the forecast window.
I would expect the icons to look like this https://cinnamon-spices.linuxmint.com/git/applets/weather@mockturtl/screenshot.png instead of how they look like here: ![weather-applet-icons](https://cloud.githubusercontent.com/assets/3486417/22377287/9440972e-e4b1-11e6-8e15-33cae09413ff.png)

I'm using Ubuntu based Mint 18. Have the latest update installed from spices.

Thanks

**Comment by NathanSalapat** [comment]
never noticed this before, but can confirm, there is a dark icon when not using the symbolic icons.

**Comment by Odyseus** [comment]
Hello, everybody.

@vpal & @NathanSalapat: Try enabling the symbolic icons option, wait a few seconds and disable it again. The same error happens if you use colored icons and want to switch to symbolics.

The problem is that, every single time that any of the applet's settings is modified, the weather data is downloaded from internet and the entire menu is re-built. And sometimes, the line 390 of the applet's code throws the following error:

```
error weather@mockturtl#: TypeError: json.get_object_member(...).get_object_member(...) is null
```

That error *halts* the correct re-build of the weather menu.

**Comment by vpal** [comment]
Greetings @Odyseus,

thanks for dealing with this.
I tried this without luck, I even waited two minutes.
This rather seems to be a permanent issue.
Even restarting cinnamon (Alt+F2 > r) or restarting the whole machine does not help here.

Thanks

**Comment by JosephMcc** [comment]
This isn't a bug. In some themes like Mint-X the icons used for the non-symbolic icons use that dark color. You can either switch icon themes or use the symbolic opiton.
