### ISSUE TITLE
Cinnamenu@json: Add more space between search categories (suggested improvement)

### ISSUE THREAD

**Issue by mfreeman72** [linuxmint/cinnamon-spices-applets#4543]
```
 * Applet version/Build date: Version 5.0.3 (2022-10-29 04:33:34)
 * Cinnamon version: Cinnamon 5.4.12
 * Distribution: Linux Mint 21
 * Graphics hardware *and* driver used: AMD Ryzen 7 APU with open source Mesa driver; NVIDIA GTX 1650 with version 520 proprietary driver

 ```

**Notify author of applet**
@fredcw

**Issue**
When using the search bar, there is a visually cramped appearance to the search categories. Would it be possible to add just one extra line of space between the categories? For example: Below the "Applications and files" section, there is "Other search results". However, that title appears slightly closer to the icon/text above it than it does to the category it's describing, and there isn't much of any real visual spacing between these sections.

**Steps to reproduce**
Do any search.

**Expected behaviour**
 Just adding a single blank text-height line between the last icon row of the "Applications and files" section and the title of the "Other search results" section might make a better visual separation between the two categories.

**Other information**
This is just a suggestion. Functionally, the applet works great! This a visual thing more than a functional thing. I'm extremely picky about things looking as good (to me) as possible, so this is just my subjective opinion.

**Comment by fredcw** [comment]
Yes, I think you're right. I didn't really give this much thought before.

You can change this spacing by adding the following to the `cinnamon.css` file of your current desktop theme:

```
.menu-applications-subheading {
    padding-top: 5px;
}
```
The padding is 0px by default on all four sides. Also, you could use for example `padding-top: 0.5em;` to make the padding proportional to the font size rather than a fixed number of pixels.

The default styling for the menu is in the file `~/.local/share/cinnamon/applets/Cinnamenu@json/4.0/stylesheet.css` where you can also change the values, but of course this is less permanent than putting the values in your current theme because all the files in the applet directory are overwritten each time the applet is updated.

I think that adding a little bit of left padding also looks slightly better. I think I might add the following to the default styling, what do you think?

```
.menu-applications-subheading {
    font-weight: bold;
    font-size: 90%;
    padding-top: 0.5em;
    padding-left: 0.3em;
}
```

Note: Don't forget to restart cinnamon after each styling change. Also, this affects the subheadings in the recents category as well.

**Comment by mfreeman72** [comment]
Thank you for the recommendations! I liked your subtle change, and you're right - It might be a good default going forward. I had some trouble implementing this, because adding it to my theme didn't seem to do anything. Adding it to the applet's css file is the only thing that worked. I also played around with values, and here's what I came up with that looked best to me, on my system:

```
.menu-applications-subheading {
    font-weight: bold;
    font-size: 125%;
    padding-top: 2em;
}
```

It's a bit more extreme than yours, so you might not like it as a default, but I like a nice, clearly defined difference between sections. I think the larger padding and large font size on the section titles really makes them pop out more clearly as titles and not just general text. Just my opinion, of course.

**Comment by fredcw** [comment]
Did you add it to your cinnamon theme ("Desktop" theme in the theme dialog) rather than the "Applications" theme? It seems to work for me. The file in the theme is usually called ~/.themes/<theme_name>/cinnamon/cinnamon.css. I originally went with smaller text to save space but maybe larger text is better. I'll try it for a while and see if it grows on me.

**Comment by mfreeman72** [comment]
Yeah, that's exactly what happened. I figured that out after I replied. Sorry for not updating you on that.
