### ISSUE TITLE
radio@driglu4it: Pop up window position doesn't change.

### ISSUE THREAD

**Issue by fredcw** [linuxmint/cinnamon-spices-applets#4562]
radio@driglu4it

```
 * Applet version 2.2.1 (2022-11-06 20:49:23)
 * Cinnamon version 5.4.12
 * Distribution - manjaro

 ```
@jonath92 

When starting or stopping play or opening or closing My stations list etc, the popup window changes size but it doesn't change it's position and so doesn't line up with the bottom panel. Have to close and then reopen the popup to get it to re-align with the panel.

**Comment by jonath92** [comment]
Yes this is too some extent on purpose. In the past the popup menu always sticked to the center of the applet container on the panel, but this was annoying when using the option "Show currrent station on the panel" and/or "show song information on the panel" of the sound applet because in that case the popup-menu moved when using the seeker which makes it very difficult to seek back (or forth) to a specific time (e.g. when a song started which you want to hear again). This is behavior is also more consistent with the sound applet (when you click here on "pause" while haven the "show song information on the panel" option enabled, it also doesn't change the position). It is a new feeling now but in my opinion it makes the popup menu more usable. But I think it is not good that the width is changing when opening the "my station list" or when starting/stopping play.

**Comment by fredcw** [comment]
I'm not sure what the solution may be but the current behaviour definitely raises some usability issues IMO.

[test-2022-11-15_10.56.39.webm](https://user-images.githubusercontent.com/58893963/201904310-b00b7e3e-540b-4bc5-9d37-d7b578ef5ed2.webm)

**Comment by jonath92** [comment]
Oh shit yes. I forgot to test it on the bottom panel... I will fix it
