### ISSUE TITLE
Cinnamenu@json: Debian Testing: "Cinnamon-subprocess-wrapper" failed.

### ISSUE THREAD

**Issue by fredcw** [linuxmint/cinnamon-spices-applets#4636]
**Issue**
Reported on applet page:

>The error appeared as soon as I installed Cinnamenu and restarted my computer and it appears for a few seconds every time I turn on my computer and enter the cinnamon environment.
Sorry for my bad english.

**Comment by fredcw** [comment]
@Fiodor1 Apart from the error, does cinnamon start normally or are you unable to boot. What version of cinnamon are you using `cinnamon --version`

What happens after you see the message?

**Comment by Fiodor1** [comment]
> @Fiodor1Εκτός από το σφάλμα, η κανέλα ξεκινάει κανονικά ή δεν μπορείτε να κάνετε εκκίνηση. Ποια εκδοχή κανέλας χρησιμοποιείτε`cinnamon --version`
> 
> Τι συμβαίνει αφού δείτε το μήνυμα; Το Cinnamenu εξακολουθεί να λειτουργεί; Τι θα συμβεί αν απεγκαταστήσετε το Cinnamenu;

Cinnamon starts normally, error occurs after boot. The cinnamon version is 5.6.5
The message appears for a few seconds, but everything seems to be working fine. When I disable the Cinnamenu and restart the error message does not appear. So I guess the Cinnamenu is responsible. 
![Στιγμιότυπο από 2023-01-08 12-10-29](https://user-images.githubusercontent.com/122111992/211190584-fd2d8a1c-d6f8-4ca7-9247-62050580cb78.png)

**Comment by fredcw** [comment]
Can you upload a copy of your `~/.xsession-errors` file after the error appears.

**Comment by Fiodor1** [comment]
> Μπορείτε να ανεβάσετε ένα αντίγραφο του `~/.xsession-errors`αρχείου σας αφού εμφανιστεί το σφάλμα.
Xsession: X session started for theodoros at Δευ 09 Ιαν 2023 06:49:53 πμ EET
dbus-update-activation-environment: setting DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
dbus-update-activation-environment: setting DISPLAY=:0
dbus-update-activation-environment: setting XAUTHORITY=/home/theodoros/.Xauthority
localuser:theodoros being added to access control list
dbus-update-activation-environment: setting GTK_MODULES=gail:atk-bridge
dbus-update-activation-environment: setting QT_ACCESSIBILITY=1
dbus-update-activation-environment: setting USER=theodoros
dbus-update-activation-environment: setting LC_TIME=el_GR.UTF-8
dbus-update-activation-environment: setting XDG_SESSION_TYPE=x11
dbus-update-activation-environment: setting HOME=/home/theodoros
dbus-update-activation-environment: setting DESKTOP_SESSION=cinnamon
dbus-update-activation-environment: setting XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
dbus-update-activation-environment: setting GTK_MODULES=gail:atk-bridge
dbus-update-activation-environment: setting LC_MONETARY=el_GR.UTF-8
dbus-update-activation-environment: setting DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
dbus-update-activation-environment: setting IM_CONFIG_PHASE=1
dbus-update-activation-environment: setting LOGNAME=theodoros
dbus-update-activation-environment: setting GTK_IM_MODULE=ibus
dbus-update-activation-environment: setting XDG_SESSION_CLASS=user
dbus-update-activation-environment: setting PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
dbus-update-activation-environment: setting GTK3_MODULES=xapp-gtk3-module
dbus-update-activation-environment: setting LC_ADDRESS=el_GR.UTF-8
dbus-update-activation-environment: setting XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
dbus-update-activation-environment: setting XDG_RUNTIME_DIR=/run/user/1000
dbus-update-activation-environment: setting DISPLAY=:0
dbus-update-activation-environment: setting LC_TELEPHONE=el_GR.UTF-8
dbus-update-activation-environment: setting LANG=el_GR.UTF-8
dbus-update-activation-environment: setting XDG_SESSION_DESKTOP=cinnamon
dbus-update-activation-environment: setting XAUTHORITY=/home/theodoros/.Xauthority
dbus-update-activation-environment: setting XMODIFIERS=@im=ibus
dbus-update-activation-environment: setting XDG_GREETER_DATA_DIR=/var/lib/lightdm/data/theodoros
dbus-update-activation-environment: setting SHELL=/bin/bash
dbus-update-activation-environment: setting LC_NAME=el_GR.UTF-8
dbus-update-activation-environment: setting GDMSESSION=cinnamon
dbus-update-activation-environment: setting QT_ACCESSIBILITY=1
dbus-update-activation-environment: setting LC_MEASUREMENT=el_GR.UTF-8
dbus-update-activation-environment: setting LC_IDENTIFICATION=el_GR.UTF-8
dbus-update-activation-environment: setting GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1
dbus-update-activation-environment: setting QT_IM_MODULE=ibus
dbus-update-activation-environment: setting PWD=/home/theodoros
dbus-update-activation-environment: setting XDG_DATA_DIRS=/usr/share/gnome:/home/theodoros/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
dbus-update-activation-environment: setting CLUTTER_IM_MODULE=ibus
dbus-update-activation-environment: setting LC_NUMERIC=el_GR.UTF-8
dbus-update-activation-environment: setting LC_PAPER=el_GR.UTF-8
discover_other_daemon: 1GNOME_KEYRING_CONTROL=/run/user/1000/keyring
discover_other_daemon: 1GNOME_KEYRING_CONTROL=/run/user/1000/keyring
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
discover_other_daemon: 1GNOME_KEYRING_CONTROL=/run/user/1000/keyring
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
[cinnamon-settings-daemon-smartcard] Failed to start: δεν βρέθηκε κατάλληλος οδηγός έξυπνης κάρτας
Αποτυχία: Ανυπαρξία τέτοιας οντότητας
[cinnamon-settings-daemon-smartcard] Failed to start: δεν βρέθηκε κατάλληλος οδηγός έξυπνης κάρτας
mutter-Message: 06:49:56.903: Enabling experimental feature 'x11-randr-fractional-scaling'
Gjs-Message: 06:49:57.330: Profiler is disabled. Not setting up signals.
Gjs-Message: 06:49:57.641: JS LOG: About to start Cinnamon
Gjs-Message: 06:49:57.807: JS LOG: [LookingGlass/info] Cinnamon.AppSystem.get_default() started in 159 ms
Gjs-Message: 06:49:57.815: JS LOG: [LookingGlass/info] loading user theme: /usr/share/themes/Hammurabi/cinnamon/cinnamon.css
Gjs-Message: 06:49:57.846: JS LOG: [LookingGlass/info] added icon directory: /usr/share/themes/Hammurabi/cinnamon

(cinnamon:1991): Gjs-WARNING **: 06:49:57.867: Some code accessed the property 'UiActor' on the module 'layout'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Gjs-Message: 06:49:58.218: JS LOG: [LookingGlass/info] loaded at Mon Jan 09 2023 06:49:58 GMT+0200 (Χειμερινή ώρα Ανατολικής Ευρώπης)
Gjs-Message: 06:49:58.218: JS LOG: Cinnamon started at Mon Jan 09 2023 06:49:58 GMT+0200 (Χειμερινή ώρα Ανατολικής Ευρώπης)
Gjs-Message: 06:49:58.219: JS LOG: GPU offload supported: false
Gjs-Message: 06:49:58.239: JS LOG: [LookingGlass/info] DeskletManager started in 1 ms
Gjs-Message: 06:49:58.239: JS LOG: [LookingGlass/info] SearchProviderManager started in 2 ms
Gjs-Message: 06:49:58.567: JS LOG: [LookingGlass/info] Loaded applet show-desktop@cinnamon.org in 217 ms
Gjs-Message: 06:49:58.618: JS LOG: [LookingGlass/info] Role locked: tray
Gjs-Message: 06:49:58.650: JS LOG: [LookingGlass/info] Loaded applet systray@cinnamon.org in 83 ms
Gjs-Message: 06:49:58.796: JS LOG: [LookingGlass/info] Loaded applet removable-drives@cinnamon.org in 146 ms
Unable to acquire bus name 'org.gnome.Software'
Gjs-Message: 06:49:58.872: JS LOG: [LookingGlass/info] Loaded applet favorites@cinnamon.org in 76 ms
Gjs-Message: 06:49:58.935: JS LOG: [LookingGlass/info] Loaded applet expo@cinnamon.org in 63 ms
Gjs-Message: 06:49:58.977: JS LOG: [LookingGlass/info] Loaded extension transparent-panels@germanfr in 42 ms

** (nemo-desktop:2053): WARNING **: 06:49:59.027: Current gtk theme is not known to have nemo support (Flat-Remix-GTK-Red-Darkest-NoBorder) - checking...
Gjs-Message: 06:49:59.081: JS LOG: [LookingGlass/info] Loaded applet scale@cinnamon.org in 104 ms
Gjs-Message: 06:49:59.319: JS LOG: [LookingGlass/info] Loaded applet user@cinnamon.org in 238 ms
Gjs-Message: 06:49:59.328: JS LOG: [LookingGlass/info] ExtensionSystem started in 1092 ms
Failed to play sound: Sound disabled
Gjs-Message: 06:49:59.650: JS LOG: [LookingGlass/info] Role locked: notifications
Gjs-Message: 06:49:59.712: JS LOG: [LookingGlass/info] Loaded applet notifications@cinnamon.org in 385 ms
Gjs-Message: 06:49:59.763: JS LOG: [LookingGlass/info] Loaded applet printers@cinnamon.org in 44 ms
Gjs-Message: 06:49:59.985: JS LOG: [LookingGlass/info] Loaded applet keyboard@cinnamon.org in 213 ms
** Message: 06:50:00.321: nemo-desktop: session is cinnamon, establishing proxy
Gjs-Message: 06:50:00.344: JS LOG: [LookingGlass/info] Loaded applet calendar@cinnamon.org in 341 ms
Gjs-Message: 06:50:00.377: JS LOG: [LookingGlass/info] Loaded applet workspace-switcher@cinnamon.org in 33 ms
Gjs-Message: 06:50:00.391: JS LOG: [LookingGlass/info] Loaded applet xapp-status@cinnamon.org in 13 ms
Fractional scaling active: False
[ main ] loading...
[ main ] 11.0.6 6.0.0-6-amd64
Trying to connect to logind...
Gjs-Message: 06:50:00.589: JS LOG: [LookingGlass/info] Loaded applet power@cinnamon.org in 198 ms
Starting screensaver...
[ main ] Loading config...
[ main ] Creating folders
[ main ] starting monitoring...
Gjs-Message: 06:50:00.645: JS LOG: [LookingGlass/info] Role locked: panellauncher
Gjs-Message: 06:50:00.645: JS LOG: [LookingGlass/info] Role locked: windowattentionhandler
[ main ] Init app
blueman-applet 06.50.00 WARNING  PluginManager:151 __load_plugin: Not loading PPPSupport because its conflict has higher priority
Gjs-Message: 06:50:00.834: JS LOG: [LookingGlass/info] Loaded applet grouped-window-list@cinnamon.org in 245 ms
blueman-applet 06.50.00 WARNING  PluginManager:151 __load_plugin: Not loading DhcpClient because its conflict has higher priority
[ main ] Loading fonts
Cinnamon Screensaver support not found in current theme - adding some...
cinnamon-session[1631]: WARNING: t+7,44383s: Detected that screensaver has appeared on the bus
Successfully using logind
Gjs-Message: 06:50:01.819: JS LOG: [LookingGlass/info] Loaded applet sound@cinnamon.org in 958 ms
Gjs-Message: 06:50:02.370: JS LOG: [LookingGlass/info] Loaded applet network@cinnamon.org in 551 ms
en
[ main ] Loading language en

(cinnamon:1991): Gjs-WARNING **: 06:50:02.507: Some code tried to set a deprecated GObject property.
0 updateUI() ["/usr/share/cinnamon/js/misc/fileUtils.js line 211 > Function":2039:45]
1 updateLoop() ["/usr/share/cinnamon/js/misc/fileUtils.js line 211 > Function":2189:17]
2 on_applet_added_to_panel() ["/usr/share/cinnamon/js/misc/fileUtils.js line 211 > Function":2291:13]
3 on_applet_added_to_panel_internal() ["/usr/share/cinnamon/js/ui/applet.js":384:13]
4 addAppletToPanels() ["/usr/share/cinnamon/js/ui/appletManager.js":413:15]
5 finishExtensionLoad() ["/usr/share/cinnamon/js/ui/appletManager.js":98:13]
6 _init/<() ["/usr/share/cinnamon/js/ui/extension.js":276:31]


(cinnamon:1991): Gjs-WARNING **: 06:50:02.508: Some code tried to set a deprecated GObject property.
0 updateUI() ["/usr/share/cinnamon/js/misc/fileUtils.js line 211 > Function":2040:45]
1 updateLoop() ["/usr/share/cinnamon/js/misc/fileUtils.js line 211 > Function":2189:17]
2 on_applet_added_to_panel() ["/usr/share/cinnamon/js/misc/fileUtils.js line 211 > Function":2291:13]
3 on_applet_added_to_panel_internal() ["/usr/share/cinnamon/js/ui/applet.js":384:13]
4 addAppletToPanels() ["/usr/share/cinnamon/js/ui/appletManager.js":413:15]
5 finishExtensionLoad() ["/usr/share/cinnamon/js/ui/appletManager.js":98:13]
6 _init/<() ["/usr/share/cinnamon/js/ui/extension.js":276:31]

Gjs-Message: 06:50:02.508: JS LOG: [LookingGlass/info] Loaded applet SpicesUpdate@claudiux in 137 ms
[ main ] Context initialized
Gjs-Message: 06:50:02.717: JS LOG: Enabling WindowAttentionHandler
Gjs-Message: 06:50:02.898: JS LOG: [LookingGlass/info] Loaded applet Cinnamenu@json in 389 ms
Gjs-Message: 06:50:02.916: JS LOG: [LookingGlass/info] AppletManager started in 4697 ms
Gjs-Message: 06:50:02.933: JS LOG: [LookingGlass/info] Cinnamon took 5289 ms to start
Gjs-Message: 06:50:02.967: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: blueman (:1.57/org/x/StatusIcon/Icon)
Gjs-Message: 06:50:03.097: JS LOG: Unknown network device type, is 14
Gjs-Message: 06:50:03.139: JS LOG: Unknown network device type, is 30
Gjs-Message: 06:50:03.249: JS LOG: [LookingGlass/info] Hiding systray: network
[ Thread-4 ] instance starting...
[ Thread-4 ] instance started.
[ Thread-4 ] Lock acquired...
checking for app update
Gjs-Message: 06:50:04.523: JS LOG: error: Η εκτέλεση του 'cinnamon-subprocess-wrapper' απέτυχε:: Αποτυχία εκτέλεσης θυγατρικής διεργασίας «cinnamon-subprocess-wrapper» (Ο κατάλογος των παραμέτρων είναι πολύ μακρύς)
Gjs-Message: 06:50:04.956: JS LOG: error: Η εκτέλεση του 'cinnamon-subprocess-wrapper' απέτυχε:: Αποτυχία εκτέλεσης θυγατρικής διεργασίας «cinnamon-subprocess-wrapper» (Ο κατάλογος των παραμέτρων είναι πολύ μακρύς)
[ Thread-3 ] manifest download response: 200
7.2.11 7.2.11

(nemo-desktop:2053): GLib-CRITICAL **: 06:50:20.519: g_hash_table_foreach: assertion 'version == hash_table->version' failed
cinnamon-session[1631]: WARNING: t+37,49338s: Detected that screensaver has left the bus

**Comment by fredcw** [comment]
Does this error appear when you restart cinnamon as well as when you reboot? (press Ctrl-Alt-Esc to restart cinnamon)

Cinnamenu reads your web browser's bookmarks for the "bookmarks search" function. It does this even if the "Web bookmarks search" option is turned off. This is the only thing I can think off that may cause the error.

You can test this in the following way:

Open the file `/home/<USER NAME>/.local/share/cinnamon/applets/Cinnamenu@json/4.0/applet.js` in a text editor and find the line which reads: `this.bookmarksManager = new BookmarksManager();`

It should be at about line 97. Comment out this line so that it reads: `//this.bookmarksManager = new BookmarksManager();` 

Save the file and restart cinnamon.

btw, thanks for your help in finding this bug.

**Comment by Fiodor1** [comment]
> Εμφανίζεται αυτό το σφάλμα κατά την επανεκκίνηση της κανέλας καθώς και κατά την επανεκκίνηση; (πατήστε Ctrl-Alt-Esc για επανεκκίνηση της κανέλας)
> 
> Το Cinnamenu διαβάζει τους σελιδοδείκτες του προγράμματος περιήγησής σας για τη λειτουργία "αναζήτηση σελιδοδεικτών". Αυτό το κάνει ακόμη και αν η επιλογή "Αναζήτηση σελιδοδεικτών Ιστού" είναι απενεργοποιημένη. Αυτό είναι το μόνο πράγμα που μπορώ να σκεφτώ ότι μπορεί να προκαλέσει το σφάλμα.
> 
> Μπορείτε να το δοκιμάσετε με τον ακόλουθο τρόπο:
> 
> Open the file `/home/<USER NAME>/.local/share/cinnamon/applets/Cinnamenu@json/4.0/applet.js` in a text editor and find the line which reads: `this.bookmarksManager = new BookmarksManager();`
> 
> It should be at about line 97. Comment out this line so that it reads: `//this.bookmarksManager = new BookmarksManager();`
> 
> Save the file and restart cinnamon.
> 
> btw, thanks for your help in finding this bug.

I applied your instructions ( //this.bookmarksManager = new BookmarksManager(); and restart Cinnamon ) and the error no longer appeared. It seems to work well.
Thank you very much.

**Comment by fredcw** [comment]
You should also turn off the option "Web bookmarks search" otherwise errors will be written to your ~/.xsession-errors file every time to use the search. I'm still not sure why you get the error and I don't but I'll look into it further.

**Comment by Fiodor1** [comment]
> Θα πρέπει επίσης να απενεργοποιήσετε την επιλογή "Αναζήτηση σελιδοδεικτών Ιστού" διαφορετικά τα σφάλματα θα εγγράφονται στο αρχείο ~/.xsession-errors κάθε φορά για να χρησιμοποιήσετε την αναζήτηση. Δεν είμαι ακόμα σίγουρος γιατί λαμβάνετε το σφάλμα και δεν το κάνω, αλλά θα το εξετάσω περαιτέρω.

I will take your advice.
Thank you for your time.

**Comment by fredcw** [comment]
@geofausto @fiodor1 I Still haven't found the cause of this bug though and haven't got a permanent solution yet. Some answers to these questions might help: Do you have a very large number of browser bookmarks, say more than 100? What browser are you using?

**Comment by Fiodor1** [comment]
> @geofausto @Fiodor1 I Still haven't found the cause of this bug though and haven't got a permanent solution yet. Some answers to these questions might help: Do you have a very large number of browser bookmarks, say more than 100? What browser are you using?

I use Google Chrome and have over 1000 bookmarks.

**Comment by geofausto** [comment]
> @geofausto @Fiodor1 I Still haven't found the cause of this bug though and haven't got a permanent solution yet. Some answers to these questions might help: Do you have a very large number of browser bookmarks, say more than 100? What browser are you using?

I use Firefox and Vivaldi (Chrome). Over 100 bookmarks.

**Comment by fredcw** [comment]
I don't think it's the number of bookmarks as I tested it with 1200 bookmarks and it seems ok. I think it's probably due to an unusual bookmark that purhaps doesn't start with "http:///" or "https://". I'll put some extra checks to make sure the applet doesn't get confused by them.

**Comment by fredcw** [comment]
Updated applet is available. Let me know if the problem is still there. Thanks.

**Comment by geofausto** [comment]
It's running without errors now. Thanks.
