### ISSUE TITLE
Unable to add new time zones

### ISSUE THREAD

**Issue by steviedeeee** [linuxmint/cinnamon-spices-applets#4637]
```
 * Applet version/Build date (to be found in "About.." or in "metadata.json")
 * Cinnamon version (cinnamon --version)
 ---5.6.5
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 ---Linux Mint 21.1 Cinnamon
 * Graphics hardware *and* driver used
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of applet**
@simonmicro

**Issue**

Unable to add new Time Zone entries.
Editing the .json at .cong/cinnamon/spices will show the location name and "+01:00" will show the time correctly in UTC relative to my current time.
However I don't see yet how to add new entries.
For example:
    "worldclocks": {
        "type": "generic",
        "default": [
            "Universal Time|+00:00"
        ],
        "value": [
            "Amsterdam|+01:00"
        ]
    },

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by fredcw** [comment]
Which applet?

**Comment by steviedeeee** [comment]
It's the World Clock Calendar by Simon Wiles.

**Comment by fredcw** [comment]
Hi, I have a temporary solution until the applet can be updated: Cinnamon was recently changed to store the applet config file in `~/.config/cinnamon/spices/<UUID>/<some number>.json` while also checking the old location just in case the file is there instead. The applet however, updates this file manually and still expects to find it in the old location. The solution is to move your .json config file to the old location so that the applet can find it.

Move the folder calendar@simonwiles.net located at `~/.config/cinnamon/spices/` to `~/.cinnamon/configs/`

Ensure that the .json file in ~/.config/cinnamon/spices/calendar@simonwiles.net/) has been deleted so that cinnamon will use the .json file in ~/.cinnamon/configs/calendar@simonwiles.net/ instead.

Restart cinnamon.

I'll see if I can update the applet but tbh, I'm not too familiar with python and it looks a bit complicated :/
