### ISSUE TITLE
xampp-panel@backids99 - Adding more shortcuts to applet

### ISSUE THREAD

**Issue by trymeouteh** [linuxmint/cinnamon-spices-applets#4705]
```
 * Applet version: 0.1
 * Cinnamon version: 5.6.7
 * Distribution: Linux Mint 21.1

 ```

**Notify author of applet**
@backids99 

When you click on the applet, there is an option to open and edit the php.ini file in admin mode. Please add the following files to also open in admin mode from the applet.

```
/etc/hosts
/opt/lampp/etc/extra.httpd-vhosts.conf
/opt/lampp/etc/httpd.conf
```

They are often access to generate new virtual hosts for different web projects.

**Comment by fredcw** [comment]
In applet.js in ~/.local/share/cinnamon/applets/xampp-panel@backids99/ here's the lines you need to add:

at line 24 add

    this.COMMAND_HOSTS_EDIT = "xed admin:///etc/hosts";
    this.COMMAND_HTTPD_VHOSTS_CONF_EDIT = "xed admin:///opt/lampp/etc/extra.httpd-vhosts.conf";
    this.COMMAND_HTTPD_CONF_EDIT = "xed admin:///opt/lampp/etc/httpd.conf";

and at line 81 (or 84 after you've added the 3 lines above) add

        this.menu.addAction(_("Edit etc/hosts"), function(event) {
                        Util.spawnCommandLine(CommandConstants.COMMAND_HOSTS_EDIT);
        });
        
        this.menu.addAction(_("Edit extra.httpd-vhosts.conf"), function(event) {
                        Util.spawnCommandLine(CommandConstants.COMMAND_HTTPD_VHOSTS_CONFIG_EDIT);
        });
        
        this.menu.addAction(_("Edit httpd.conf"), function(event) {
                        Util.spawnCommandLine(CommandConstants.COMMAND_HTTPD_CONFIG_EDIT);
        });

Edit the variable names and menu text strings as you see fit. Also, since the applet has no current author, you could try submitting a pull request yourself?
