### ISSUE TITLE
weather@mockturtl Hourl Weather Redesign

### ISSUE THREAD

**Issue by Gr3q** [linuxmint/cinnamon-spices-applets#4780]
![Screenshot from 2023-03-31 09-20-09](https://user-images.githubusercontent.com/22377521/229066485-8727daf8-f863-4f5f-9f05-6a43197f32a5.png)

As you can see the picture I desperately need some help from a UX/designer person to make this look ok and informative. It can be completely different. My main paint point is representing precipitation in a manner that you can tell when it's going to rain at a glance.

I have the information if you are using dark/light theme but not the theme colors.

PS.: The icons most likely won't be colored.

**Comment by Severga** [comment]
I'm not a good designer but my suggestion is the background - e.g. tints of blue for wet and tints of orange for dry weather

**Comment by jorgenqv** [comment]
Very good idea! Nice with the temp graphs and rain bars, think it make things more easy to quickly grasp upcoming weather. Not a pro UX guy either, more of a enthusiast, and totally agree on not using colored icons. Here are some thoughts:

- The middle Hourly area is very crowded and repetitive. You could show every second or third hour instead and layout them in blocks like from noon to three or six and so on. The bottom blue bars for rain can still be for every hour in the background. Some inspiration is dmi.dk that I think is very clear and easy to see – https://www.dmi.dk/lokation/show/GB/2653941/Cambridge/ or the old style here: http://servlet.dmi.dk//byvejr/servlet/world_image?city=2653941&mode=dag1_2

-  The background graphs and bars should be more discreet like transparent if possible, to work in both dark and light themes. You should stick with red for temp and darker blue if freezing temp, light blue for rain/snow. 

-  Hourly info regarding wind would be nice to have! I think you could fit it in there of you can make one row instead of two for rain and remove decimals, like “2mm (78%)” and arrows for wind directions followed by strength like “←8” on the row below.

**Comment by Gr3q** [comment]
I ran out of time on the other one, I did like the idea of having wind info for hourly weather tho.

Please open new issues if you dislike the implementation.
