### ISSUE TITLE
Question Regarding Usage : calc-js@ptandler

### ISSUE THREAD

**Issue by henri** [linuxmint/cinnamon-spices-applets#4851]
@ptandler

Just wondering how you commit a calculation to the history. Do you press a button or have to format the expression a certain way?

**Steps to reproduce**
1 + 2 [press enter key]

**Expected behavior**
see the expression and possibly the result in history

**Other information**
I am guessing this is not a bug - but just a misunderstanding of using this excellent applet?

**Comment by ptandler** [comment]
What you describe as expected behavior is exactly how it should work: You type an expression and press enter and it shows up in the history.

Actually the result should show up immediately after typing, no need to press enter.

So this does not work for you?

Maybe, there is something in the logs, that gives a hint what is different in your environment?
https://stackoverflow.com/q/14025722/1480587

**Comment by fredcw** [comment]
Same here. History menu just remains greyed out. Nothing in ~/.xsession-errors.

**Comment by ptandler** [comment]
but evaluating the expression works?

**Comment by ptandler** [comment]
ah, maybe you use a different cinnamon version?

I still have 5.2.7 on my machine (and mint 20.3 as the upgrade to 21 did not work)

I think I read that the CJS version was upgraded with this release

**Comment by fredcw** [comment]
@ptandler Yes, i tested on cinnamon 5.6 and 5.8. Cjs is updated in 5.8 but that shouldn't make a difference. Clutter was updated in 5.4 https://github.com/linuxmint/cinnamon-spices-applets/issues/4364
