### ISSUE TITLE
Toggle switch for the hourly weather display (weather@mockturtl)

### ISSUE THREAD

**Issue by SciTecDC** [linuxmint/cinnamon-spices-applets#4964]
* Applet version: 3.2.13
 * Cinnamon version: 5.6.8
 * Distribution: LMDE 5
 
 **Steps to reproduce**
There is an issue with the hourly weather toggle button, which only occurs under certain conditions. Access to said button is no longer possible if 1. the toolbar is set to hide either automatically or intelligently and 2. the window of any application has been maximized at the same time. Although the toggle switch is initially visible under these conditions, when pressed it only opens the hourly weather display, after which it appears to hide behind the toolbar and can no longer be used to close it.

The phenomenon does not occur if the toolbar remains permanently visible and/or any application's window has been minimized or switched down on the toolbar, regardless of how the toolbar is configured. While this doesn't impede the information you want to see, it certainly isn't correct.

**Expected behaviour**
The toggle switch for the hourly weather display should remain visible under all circumstances and not disappear seemingly behind the toolbar.

**Comment by Drugwash2** [comment]
If I'm not mistaken this issue does not pertain to this applet - or any applet for that matter - but to Cinnamon itself. For what it's worth such thing has been happening since forever with the 'Download and upload speed' applet's so-called tooltip which in reality is a menu window. Observed here in Mint 19.2 (Cinnamon 4.2) with the main panel placed at the top and set to autohidden.

**Comment by Gr3q** [comment]
I see what you mean. It looks like it's a bug in Cinnamon.
Because the popupMenu is resizing, popupMenu.js->[_allocationChanged](https://github.com/linuxmint/cinnamon/blob/2faa38d93fb5e1cac95e42662153e3fe2266ffb2/js/ui/popupMenu.js#L2675)->[_calculatePosition](https://github.com/linuxmint/cinnamon/blob/2faa38d93fb5e1cac95e42662153e3fe2266ffb2/js/ui/popupMenu.js#L2596) is called, that checks if the panel is visible or not.

In this case it reports that the panel is not visible, even though it is. This is how far I've gotten so far.

I'll try to spend time on it and see what goes wrong inside `panel.js`, but the fix will need to be in Cinnamon. If there is a workaround for the applet I'll try to do that as well.
