### ISSUE TITLE
hwmonitor@sylfurd Feature Request: option to hide some graphics

### ISSUE THREAD

**Issue by Cyrille37** [linuxmint/cinnamon-spices-applets#5065]
### Applet name and maintainer

hwmonitor@sylfurd @hultan

### What would you like to see?

Hi

Thanks a lot for this great applet, it's nice.

Do you think possible to add settings to hide (or show) some graphics. For example I would like to not display the "BAT" and "MEM" graphics.

Thanks & Cheers :-)

**Comment by fredcw** [comment]
@Cyrille37 Due to a bug, the page tab titles in the config dialog are not visible when first opened. Widen the config window to access the tabbed pages and turn off the graphs you don't want.

**Comment by Cyrille37** [comment]
Yeah! Thanks :-)

But it's not the first time, but the with which shows tabs.

![image](https://github.com/linuxmint/cinnamon-spices-applets/assets/368965/531e3d59-6cb1-47e2-95a4-e3db9eb83600)

![image](https://github.com/linuxmint/cinnamon-spices-applets/assets/368965/5d659aca-44e4-4017-beb7-6d66b6fb2498)

**Comment by Hultan** [comment]
> @Cyrille37 Due to a bug, the page tab titles in the config dialog are not visible when first opened. Widen the config window to access the tabbed pages and turn off the graphs you don't want.

Oh, so that is why the tabs are sometimes not visible? I have never seen this happen on my machine, so I have given up on solving this bug. Thanks for fixing this bug @fredcw! I hope someone accepts the PR soon, I don't have permission to do that.

BTW, feel free to take over this applet by changing the `author` field in `info.json` file. I doubt that I will do more work on this applet.

**Comment by Cyrille37** [comment]
Thanks guys

I made the update, it's better :-) but it's not exhaustive :-(

Tabs are now visible with a smaller window
![image](https://github.com/linuxmint/cinnamon-spices-applets/assets/368965/cdcd1774-cc11-4148-a471-2927bbc293e8)

But with an even smaller window they disappear again
![image](https://github.com/linuxmint/cinnamon-spices-applets/assets/368965/36f31566-b13c-4c30-9cdb-aebe04aa4de2)

Thanks & cheers :-)

**Comment by fredcw** [comment]
@Cyrille37 Ultimately this is a cinnamon bug. But one workaround is to change the french translation of "Memory" from "Mémoire vive" to "RAM". Btw, it looks like your using Adwaita theme which makes all the tabs the same width whereas most themes make each tab width fit the label. I'm only suggesting workarounds here because I'm not sure how easy this will be to fix in cinnamon.

**Comment by fredcw** [comment]
@Cyrille37 There's something I don't understand here. It seems "Memory" is being translated to "Mémoire vive" in the config dialog but I cannot find this translation in the applet's `fr.po` file. Have you added your own custom translations to this applet?

**Comment by claudiux** [comment]
When I search "Memory" in .mo files, I find:
```
cinnamon:
	Mémoire vive
geany-plugins:
	Mémoire
gnome-applets:
	Mémoire
```

Furthermore, "Memoty" is not present in the `hwmonitor@sylfurd.pot` file.

**Comment by fredcw** [comment]
@claudiux Thanks. Yes, it seems that seems that cinnamon translates strings that are not in the .po files of the applet - I didn't know this. In any case, I just tested translating "Memory" to "RAM" in fr.po of the applet. It changes the translation in the applet but it doesn't make a difference to the tab bar width. It seems that the adwaita theme has a minimum with for the tabs regardless of the label width so this solution isn't going to work anyway.

I guess the only real solution is to fix it in cinnamon so that the widow is automatically wide enough for the tab bar.

**Comment by Cyrille37** [comment]
Thanks all to manage this bug, it's great :-)
