### ISSUE TITLE
pomodoro@gregfreeman.org - missing darkscreen

### ISSUE THREAD

**Issue by Jopp-gh** [linuxmint/cinnamon-spices-applets#5562]
### Applet name and maintainer

pomodoro@gregfreeman.org @gfreeau

## Problem
Very nice applet with a load of options,but there is no motivation to take a break if the screen shows just some notification. 

## Feature
I would expect a dismiss-able dimmed screen - or the screensaver - or two slots to execute user code after and / or before a break for max customization 

## Other info
I tried another applet called Timeout but it seems not to play well with Virginia, because I cannot dismiss the dialog and have to shut down my pc.

**Comment by gfreeau** [comment]
Hi @Jopp-gh so I understand your request, can you first try the applet with these settings:

![image](https://github.com/linuxmint/cinnamon-spices-applets/assets/1403669/e220de15-86ad-45bc-8483-9a7557fa4d4f)

If you turn on dialogs and turn off auto start after breaks it will show a dialog you need to dismiss rather than a notification. Can you confirm you have tried this because when I read your request that's what I think of.

**Comment by gfreeau** [comment]
Hmm I'm not quite getting what's missing here. 

I just checked the dim screen when you remove an applet as you suggested. It dims the screen behind the confirmation dialog. Here is what I see:

![image](https://github.com/linuxmint/cinnamon-spices-applets/assets/1403669/32323a9d-41c4-4350-a415-e4f2b8494775)

This applet already does that same thing, here is an example of the pomodoro end dialog: 

![image](https://github.com/linuxmint/cinnamon-spices-applets/assets/1403669/9c77985b-f968-44eb-ac7b-4ae179fd4508)

and here is pomodoro set end (start of long break):

![image](https://github.com/linuxmint/cinnamon-spices-applets/assets/1403669/46b6187e-7048-407d-86fc-4a3b2efbe299)

This happens if you disable the auto start options and enable dialog messages like in the screenshot I gave you in an earlier message.

I don't like to idea of activating and deactivating the screensaver automatically, if the user wants to do that, they can configure a keyboard shortcut to do that already. I think that would complicate the applet.

**Comment by gfreeau** [comment]
Ok I understand your point and have an idea.

The long break dialog behaves differently to the pomodoro end and short break dialog. If you have dialog turned on a long break dialog automatically starts the timer and the dialog itself shows the countdown. The user can choose to hide this dialog if they want. If autostart is turned on, it will auto dismiss this dialog at the right time. Here it is again: 

![image](https://github.com/linuxmint/cinnamon-spices-applets/assets/1403669/08d05253-5307-4288-8656-6e0bb3df9262)

So I'm thinking if we adopt this type of dialog for the other timers such as pomodoro and short timer, it would solve your problem. If the user doesn't wish for the dialog to stay open they can click the hide button or just turn on the auto start option for that timer, which shows no dialog at all.

What do you think?

**Comment by gfreeau** [comment]
@Jopp-gh Version 1.0.2 has the new options to run a script when short and long breaks start. The scripts need execute permission. Here is the PR: https://github.com/linuxmint/cinnamon-spices-applets/pull/5949
