### ISSUE TITLE
Add support for gitmodules

### ISSUE THREAD

**Issue by axos88** [linuxmint/cinnamon-spices-applets#60]
If an applet is using their own github project, allow them to be included as gitmoudles or using a reference to the user/repo/branch which is considered "production ready", and where files should be downloaded from to prepare the zip files.

**Comment by NikoKrause** [comment]
I think this was discussed somewhere else. But I can't find it right now.
This would overcomplicate the whole process and costs more time for the reviewers. Also it would limit the possibility to fix broken applets or to fix stuff in advance before new Cinnamon versions are released.

I never worked with gitmodules and can't judge this. Maybe I reproduced the arguments wrong.

@clefebvre can explain it better than I do.

**Comment by axos88** [comment]
Referring to a specific commit can solve your concerns about QA

**Comment by lestcape** [comment]
Definitely, if this is implemented i will take care to continues supporting Cinnamon in my applets and desklets, if not, i can not.

Let to users decide what they want to do. Of course, they can be alerted that this is not an "spices" extension with an official review for Mint in some way, if that it's the problem.

Three-party repositories exist for a reason...

This is like "The Mint update" (that i also dislike and it's the main reason of why i don't use Mint). This is a way to remove the freedom of the users and developers authority. But it's worse, because there are ways to bypass the levels of restriction in Mint update. Here there are not way.

The free software it's without warranty by law, cinnamon is without warranty by law, mint it's without warranty by law. Then, this is only an imposition of a police human authority. That in fact this is only a limit to users and developers. If you are not with me, you can not.

**Comment by jaszhix** [comment]
I think we are not using git modules because it circumvents our ability to check for security and stability issues with xlets. I'll close for now.
