### ISSUE TITLE
weather@mockturtl: Incorrectly formatted text

### ISSUE THREAD

**Issue by LLKoder** [linuxmint/cinnamon-spices-applets#6011]
### Applet version/Build date

3.4.3 (2024-05-08 20:04:43)

### Cinnamon version

6.0.4

### Distribution

LMDE 6

### Graphics hardware *and* driver used

no discrete card, CPU-card, laptop

### Applet name and maintainer

weather@mockturtl @Gr3q

### What happened?

![2024-05-15_12-29](https://github.com/linuxmint/cinnamon-spices-applets/assets/50442676/70823eae-3183-4160-9ce7-5235a83b364e)

At screenshot can see incorrectly formatted text.
First part: squeeze text after I click "Refresh". I can't read this. After a lot of click "Refresh" I may be can see correct formatted text.
Second part: the text/images is aligned to the left rather than centered.

**Comment by Gr3q** [comment]
Hi, the problem with the current weather section is known, I will try to spend some time on it, but it's quite an elusive problem.

The one with the hourly weather is because I'm drawing a graph and it has to be a set size per hour and the scroll view width is calculated in a weird way so I couldn't do centering or spanning before if there are not enough hours to fill the space. I will see what I can do about it.

**Comment by rcalixte** [comment]
@Gr3q Take a look at the Pango class. The weather desklet had a similar problem and makes use of this now. Hopefully this helps!
