### ISSUE TITLE
weather@mockturtl: arrow missing

### ISSUE THREAD

**Issue by Axel-Erfurt** [linuxmint/cinnamon-spices-applets#6033]
### Applet version/Build date

3.5.0

### Cinnamon version

6.0.4

### Distribution

LMDE6

### Applet name and maintainer

weather@mockturtl @Gr3q

### What happened?

the arrow to expand view has disappeared.

**Comment by Gr3q** [comment]
Indeed, this is because I can't guarantee the same level of features with the OpenWeatherMap opensource key that we have from June.

If you'd like to stay on OpenWeatherMap, you need to get an api key from OpenWeatherMap and switch to the `OpenWeatherMap OneCall` provider, or switch to Open-Meteo which doesn't have minutely forecast nor alerts, but doesn't need a key.

**Comment by Axel-Erfurt** [comment]
Thanks for the reply. I changed the provider to “Deutscher Wetterdienst”, so it works as usual.

**Comment by rcalixte** [comment]
Is this okay to be marked as resolved?

**Comment by Axel-Erfurt** [comment]
Yes

**Comment by janos-r** [comment]
I switched to "open-meteo" and everything works as expected :)
