### ISSUE TITLE
multicore-sys-monitor@ccadeptic23: Net panel with docker unscrollable

### ISSUE THREAD

**Issue by tchiotludo** [linuxmint/cinnamon-spices-applets#681]
When using docker, there is a lot of network created : 

![image](https://cloud.githubusercontent.com/assets/2064609/26093670/24d9b576-3a17-11e7-9741-32378eb9a176.png)

The window doesn't allow scrolling to disabled the network interface you don't care.
The best will be to disable by default all docker and virtualbox interface since only few people will look at these one.

**Comment by tchiotludo** [comment]
@NikoKrause : thanks for the information, i wasn't aware :smile: 
@jaszhix

**Comment by jaszhix** [comment]
I use Docker too, and was able to reproduce this.

**Comment by tchiotludo** [comment]
@jaszhix : Still have the issue here.
I upgrade the applets, I see that I can resize the pref page horizontaly but I can't vertically.
The page is too long so I can't see the bottom.
I think we really need a scrollable window in for this page

**Comment by jaszhix** [comment]
I'm able to resize it vertically, or do you mean you ran out of screen real estate? I'm a bit out of my element with this Glade stuff but I'll look into it again soon.

**Comment by tchiotludo** [comment]
yes the window height is larger than my screen height.
On the screenshot above, the gray bar is the bottom panel bar.
I have many (15 and more) docker image running

**Comment by evg-zhabotinsky** [comment]
My 2¢ on how it could be solved:

Have a list of regular expressions (plus implicit `.*` last), put every NIC into the first group it matches.
Then basically work with those groups instead of separate NICs.

I think it's the easiest, yet sufficient, solution for autogenerated NICs and NIC grouping in general.
I would be happy with having regex list as a text input field, but it could be fancier if someone had time to implement a reorderable list with editable name, regex and 2 colors for each row.
