### ISSUE TITLE
network@brownsr : Add Scrollbar in each section if list exceeds screen height

### ISSUE THREAD

**Issue by deepsidhu1313** [linuxmint/cinnamon-spices-applets#750]
@brownsr Please add scrollbars in each section if list exceeds limited entries. On my screen, list is going out of bounds. 

And i am not sure about how mobile broadband section was suppose to work. But even disabled, it is showing list of available networks.

**Comment by brownsr** [comment]
@deepsidhu1313 I'd be grateful if you could give a screenshot of the problem.  This is an incredibly simple applet, which is designed to give the same result as the network desktop icon, so that desktop icons can be turned off and this applet used instead - for those that like an empty desktop.  As such it triggers - or should trigger - the standard display you will see when clicking on the desktop network icon, or if in nemo selecting  Go Network   or else typing network:/// into the bar.  So unless something very weird is happening, any issue will lie somewhere other than in this applet.  A screenshot of the problem you see will help to get to the bottom of this.

**Comment by deepsidhu1313** [comment]
Here is the screenshot.
![screenshot nm](https://user-images.githubusercontent.com/7684338/27808984-86a9c460-6011-11e7-9a5a-963bc5b1543d.png)

I guess this is standard 'Network Manager' applet. My apologies for the trouble. Thanks for the help.
