### ISSUE TITLE
rancher@centurix: Homestead manager applet menu freezes after right click

### ISSUE THREAD

**Issue by moretocome** [linuxmint/cinnamon-spices-applets#884]
@Centurix 

Thanks a lot for the recent updates of the Homestead manager applet. This is one of my favorite Cinnamon applets. I didn't know about Homestead before seeing this applet, and know I use it for all my development projects so thank you for crating it! :)

I found another small bug. If I left click the applet icon in the panel to open the Homestead menu and then immediately right click the applet icon to open the applet context menu (to get to the applet configuration), the left click Homestead menu freezes and will not close.

Clicking the Homestead menu can even make Cinnamon freeze totally with not options left but a hard reset of the PC, but restarting cinnamon (before freezing of course) fixes the issue.

I'm running the latest stable Linux Mint 18.1 with Cinnamon 3.2.7 and everything updated through Update Manager.

**Comment by Centurix** [comment]
Ah, I see it. Thanks, I'll investigate and post a fix up soon.

**Comment by Centurix** [comment]
As an interim, to make the stuck menu disappear, just restart the Cinnamon part by doing ALT+F2, then 'r' and enter without the quote marks. It'll restore the windows back to where they were, but the stuck menu will disappear. It must be something to do with how I invoke the configuration menu as I get the same issue with one of my other applets, Cheaty. :)

I should be able to get to the resolution within the next 8 hours or so.

**Comment by Centurix** [comment]
Posted a PR to resolve this issue: #885 
Weird behaviour caused by using the built in IconApplet _menuManager. Doesn't seem to play nice with right click context menus.

I use Homestead for any PHP work I perform, Symfony, Laravel or Lumen. It's fast and easy to configure. This applet was to scratch an itch I had, and I actually wasn't aware anyone else was using it! I've never found any download stats for Applets to be honest.

Again, thanks for the feedback, happy days!

**Comment by moretocome** [comment]
Again thanks for the applet and the updates. At least I'm a happy user, but I would suspect more exists :)

Issue confirmed to be resolved.
