### ISSUE TITLE
[some applets] show a warning message in system setting

### ISSUE THREAD

**Issue by kmkom** [linuxmint/cinnamon-spices-applets#938]
CPU Temperature Indicator
@fevimu
Vboxlauncher
@mockturtl

[Issue]:
Some applets (two examples listed above) show a red exclamation mark within the system setting tool (see screen shot). I'm not sure what causes this and if this could be fixed by the developers? A fix would be fine i think because the message may worry some users...
System: Linux Mint 18.1 Cinnamon 64-bit, v. 3.2.7

![applet-warning](https://user-images.githubusercontent.com/15555865/27509117-e3dde378-58f5-11e7-8245-d4a5bfb99a9e.png)

**Comment by jaszhix** [comment]
It means these applets use API calls that can change files on your system an do I/O. They're not *dangerous* as long as the author of the applet is careful, and applets are now reviewed for security and quality before being published. The dangerous flag is set on a number of applets, and the Cinnamon repo would be a better place to discuss whether or not these applets are being flagged appropriately.

**Comment by kmkom** [comment]
>applets use API calls that can change files on your system and do I/O
I'm not sure that your comment is correct because the message pop-up does not say anything in that direction. I think this message it is misleading (and probably useless).
And why do you think that this is an discussion for the Cinnamon repro? Does Cinnamon has a "list" of "flags" of all applets and controls this flag central?

**Comment by Odyseus** [comment]
Hello, everybody.

@kmkom: A more correct description of what that message informs about is "*API calls that made synchronous operations, regardless if they do I/O operations or not*".

What that flag really informs about is the existence of the `spawn_sync`, `spawn_command_line_sync`, `GTop` and `get_file_contents_utf8_sync` strings in the xlets code. It doesn't matter if those strings are actual function calls or if they are inside a comment. The xlets will be flagged regardless.

The use of the previously mentioned function calls can cause slow downs and freezes due to their synchronous nature. The message that you see informs exactly about that, so is not misleading nor useless at all.
