### ISSUE TITLE
Zeripaths Window list: applet is broken

### ISSUE THREAD

**Issue by NikoKrause** [linuxmint/cinnamon-spices-applets#943]
@zeripath When I add your window list applet (on Cinnamon 3.2.7), all I get is a blank space in the panel.

**Comment by zeripath** [comment]
Hmm... interesting. It appears to be working fine for me (I'm currently on version 3.4.1 but I guess I've been through 3.2.7 at some point and I've not had to change the code in 3 years!)

OK let's try to work out what's going on. 

* What is the result of:
`(dconf read /org/cinnamon/enabled-applets | grep zeripath > /dev/null) && echo "enabled" || echo "disabled"`
(This will let me make sure that it's actually enabled - if it's not then have you run the `install.sh` script and have the `dconf` program from the `dconf-tools` package?)
* Do you have any logs that I can look at to see where the problem is? Take a look at `~/.cinnamon/glass.log`  Is there anything helpful in there to explain what's going on? Or could you give me a copy of it?

If it is *enabled* and there is nothing in the logs to explain why it's not working then we should take a look at the geometry of your panels. 

* Could you show me the results of: 
`dconf read /org/cinnamon/enabled-applets`
* Does running the `uninstall.sh` script restore a working original window-list applet? If not there is definitely something screwy going on with your panels. (The `install.sh` can be run to replace/reinstall my applet to the correct place as necessary.)

HTH

**Comment by Cobinja** [comment]
Happens for me too. After a cinnamon restart, all windows are there, so it seems it doesn't correctly load existing windows, when it's added to the panel

**Comment by zeripath** [comment]
Ah! That's to be expected. As per the Readme file:

> 1. Install dconf-tools: `sudo apt-get install dconf-tools`
> 2. Extract the zip into a temporary directory
> 3. `cd` into that directory
> 4. `chmod +x install.sh`
> 5. `./install.sh`
> 6. Press `ALT-F2`, type `r`, and press `ENTER` to restart cinnamon.
>
> The install script will replace the default cinnamon window-list with my version of the applet.

The `ALT-F2 r` is needed to ensure that the list-applet gets told about the running programs by cinnamon. When I wrote the applet there was no way of querying cinnamon to get this list on addition and cinnamon wasn't properly resizing panels to fit the applet - so it seemed like the correct thing to do was to require an restart through `ALT-F2 r`. 

I can take a look at seeing if there is a way to avoid having to restart with `ALT-F2 r`.

**Comment by zeripath** [comment]
So, looking at the source code for the `window-list@cinnamon.org` applet I have currently installed on my computer, there has been some change of functionality regarding updating of watched monitors. Perhaps that fixes things, I also note that other features have been added - I think I'll update my patches.

**Comment by zeripath** [comment]
OK I've pushed an update to this to my repository at https://github.com/zeripath/cinnamon-applets There's still an issue with this - I can't seem to get the settings bit to work. Do either of you understand why this isn't working?

**Comment by zeripath** [comment]
Hi @NikoKrause and @Cobinja, could you check whether the above merge fixes your problems?

**Comment by jaszhix** [comment]
It works fine for me.
