### ISSUE TITLE
 temperature@fevimu: Applet doesn't start after Upgrade to Sonya 18.2

### ISSUE THREAD

**Issue by dobinator** [linuxmint/cinnamon-spices-applets#978]
LSB Version:	core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID:	LinuxMint
Description:	Linux Mint 18.2 Sonya
Release:	18.2
Codename:	sonya
Cinnamon 3.4.3

`error t=2017-07-04T09:19:23.838Z No JS module 'panelMenu' found in search path
trace t=2017-07-04T09:19:23.838Z 
<----------------
@/home/myname/.local/share/cinnamon/applets/temperature@fevimu/applet.js:3:7
Extension.prototype._init@/usr/share/cinnamon/js/ui/extension.js:155:13
Extension@/usr/share/cinnamon/js/ui/extension.js:116:5
loadExtension@/usr/share/cinnamon/js/ui/extension.js:449:25
onEnabledAppletsChanged@/usr/share/cinnamon/js/ui/appletManager.js:236:13
---------------->
error t=2017-07-04T09:19:23.838Z [Applet "temperature@fevimu"]: Error importing applet.js from temperature@fevimu
error t=2017-07-04T09:19:23.838Z Could not load applet temperature@fevimu`

**Comment by NikoKrause** [comment]
You need to update the applet.
SystemSettings->Applets->AvailableApplets(online)->Resfresh List-> Apply updates

**Comment by madscientist42** [comment]
Being that this is LinuxMint's own tracker, etc.  "You are using an old version." isn't a VALID answer, @NikoKrause to be blunt about it.  If it got broke on an update to 18.2 (Mine did...), and 18.2's been out for HOW long?  (July...this is SEPTEMBER) then someone's screwed it all up.  Closing it when it's been "fixed" and yet not is the same mentality that systemd's bunch has that earned them a Pwnie this year.  I don't consider this a good thing.

FIX IT in updates for 18.2 and DON'T close it until the updates go out.

**Comment by madscientist42** [comment]
This isn't like windows where this is a separate program and ran as a separate update system- this is part of MINT.

**Comment by NikoKrause** [comment]
The applets have to be updated manually.
The `panelMenu` module has been removed in 18.2 and the applet has been fixed on 25 April. Which means that the update of this applet is available since 25 April (for all Cinnamon/Mint versions)
If you upgrade from 18.1 to 18.2 and had the applet already installed, it won't get updated automatically. You have to refresh the list and apply the updates.

Spices are not part of MINT. They are only available for/through Cinnamon. They are 3rd party applets/desklets/extensions/themes. This spices repo and the review process of the spices is pretty new (since January 2017).

Right now there's no option to update applets automatically. But the Mint team is aware of this issue.
For now all I can do, is to tell you how to update your applet manually.
If it's still broken for you after you updated it, let us know.
